# Time Series Forecasting with BrainAutoMLForecast

Multi-stock, multi-horizon forecasting using the `brain_automl` package API.

| Step | API |
|------|-----|
| 1 | Load **full dataset** with `load_stock_forecasting_dataset(..., last_n_days=0)` |
| 2 | `model = BrainAutoMLForecast(...)` |
| 3 | `model.fit_all_stocks(df, horizons=[7, 15, 30])` — trains once per stock, evaluates at multiple horizons |
| 4 | `model.multi_stock_leaderboard()` — full results with stock, horizon, model, rmse, mae, mape |
| 5 | `model.best_model_per_stock()` — best model per stock × horizon |
| 6 | `model.overall_best_models()` — top models by mean RMSE across all stocks |

**Key Features:**
- ✅ Full dataset (no time restriction)
- ✅ Train once per stock on all data except last 30 days
- ✅ Evaluate at 7, 15, and 30-day horizons from the same trained model (efficient!)
- ✅ Per-stock leaderboard with stock name, horizon, model, library
- ✅ All AutoGluon internal models exposed (ag_DeepAR, ag_TemporalFusionTransformer, etc.)
- ✅ Univariate vs Multivariate comparison
- ✅ Visualization: RMSE by stock, horizon degradation charts

Set `include_comprehensive=True` to run classical decomposition × model sweep.  
Set `include_advanced_dl=True` to run BiLSTM / Transformer / AttentionForecaster / HybridStack (requires TensorFlow).

In [1]:
from pathlib import Path
import sys

import pandas as pd
import plotly.express as px

PROJECT_ROOT = Path.cwd().resolve().parent
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

from brain_automl.data_processing import load_stock_forecasting_dataset
from brain_automl.model_zoo.time_series_ai import BrainAutoMLForecast

In [2]:
data_path = Path.cwd() / "dataset.csv"
df = load_stock_forecasting_dataset(
    data_path=data_path,
    date_col="Date",
    group_col="Stock",
    target_col="Close",
    last_n_days=0,  # Use full dataset
)

print(f"Rows: {len(df):,}  |  Stocks: {df['Stock'].nunique()}  |  Columns: {list(df.columns)}")

Rows: 18,381  |  Stocks: 5  |  Columns: ['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Return', 'MA_5', 'MA_10', 'MA_20', 'Volatility', 'Stock']

In [3]:
# Multi-horizon training: trains once per stock on all data minus last 30 days
# Then evaluates at 7, 15, and 30-day horizons from the same trained model

model = BrainAutoMLForecast(
    horizon=30,  # Max horizon for training
    timestamp_column="Date",
    target_column="Close",
    item_id_column="Stock",
    include_backends=True,         # AutoGluon / StatsForecast / FLAML / Chronos
    include_comprehensive=True,   # ARIMA / LSTM / XGBoost / RF + decomposition sweep
    include_advanced_dl=True,      # BiLSTM / Transformer / Attention / HybridStack (needs TF)
)

# Trains once per stock, evaluates at multiple horizons
model.fit_all_stocks(df, horizons=[7, 15, 30])
print(model)

[22:25:56] INFO     Brain-AI run started
[22:25:56] INFO     Log file : /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/logs/brain_automl_20260406_222556_485269.log
[22:25:56] INFO     Output dir: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output
[22:25:56] INFO     ============================================================
[22:25:56] INFO     fit_all_stocks() starting
[22:25:56] INFO       Data shape  : (18381, 12)
[22:25:56] INFO       Horizons    : [7, 15, 30]  (max=30)
[22:25:56] INFO       Target      : Close
[22:25:56] INFO       Item-ID col : 'Stock'
[22:25:56] INFO     ============================================================
[22:25:56] INFO     Stocks to process: ['BANKNIFTY', 'HDFCBANK', 'NIFTY50', 'RELIANCE', 'TCS'] (5 total)
[22:25:56] INFO
──────────────────────────────────────────────────
[22:25:56] INFO     [1/5] Stock: BANKNIFTY
[22:25:56] INFO     Item: BANKNIFTY | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[22:25:56] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[22:26:22] INFO     [ OK ] autogluon_timeseries — 26.0s | RMSE=1895.6280  MAE=1571.1698
[22:26:22] INFO     [START] statsforecast
[22:26:24] INFO     [ OK ] statsforecast — 1.5s | RMSE=1784.9661  MAE=1476.8209
[22:26:24] INFO     [START] flaml
[22:27:15] INFO     [ OK ] flaml — 51.4s | RMSE=1748.1605  MAE=1467.2402
[22:27:15] INFO     Best backend: ag_DirectTabular | RMSE=1060.0958  MAE=848.3960
[22:27:15] INFO     forecast_last_horizon complete
[22:27:15] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/predictions/BANKNIFTY_predictions_h30.csv
[22:27:15] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[22:27:15] [comprehensive] ── Stock: BANKNIFTY  (train=3647, test=30 rows)
[22:27:15] [comprehensive] combo 1/15 | BANKNIFTY/Close | decomp=original model=ARIMA
[22:27:15] [comprehensive]    ✓ RMSE=2205.7558  MAE=1925.9493  MAPE=3.6550
[22:27:15] [comprehensive] combo 2/15 | BANKNIFTY/Close | decomp=original model=ExpSmoothing
[22:27:15] [comprehensive]    ✓ RMSE=2058.7864  MAE=1752.5557  MAPE=3.3221
[22:27:15] [comprehensive] combo 3/15 | BANKNIFTY/Close | decomp=original model=LSTM
[22:28:37] [comprehensive]    ✓ RMSE=6591.4638  MAE=6473.4533  MAPE=12.3798
[22:28:37] [comprehensive] combo 4/15 | BANKNIFTY/Close | decomp=original model=XGBoost
[22:28:37] [comprehensive]    ✓ RMSE=1638.3722  MAE=1346.6321  MAPE=2.5590
[22:28:37] [comprehensive] combo 5/15 | BANKNIFTY/Close | decomp=original model=RandomForest
[22:28:38] [comprehensive]    ✓ RMSE=1567.8091  MAE=1270.1647  MAPE=2.4188
[22:28:38] [comprehensive] combo 6/15 | BANKNIFTY/Close | decomp=decomposition+model model=ARIMA
[22:28:38] [comprehensive]    ✓ RMSE=22621.4369  MAE=22595.9180  MAPE=43.3390
[22:28:38] [comprehensive] combo 7/15 | BANKNIFTY/Close | decomp=decomposition+model model=ExpSmoothing
[22:28:38] [comprehensive]    ✓ RMSE=22613.3356  MAE=22587.7180  MAPE=43.3232
[22:28:38] [comprehensive] combo 8/15 | BANKNIFTY/Close | decomp=decomposition+model model=LSTM
[22:31:07] [comprehensive]    ✓ RMSE=27990.6263  MAE=27965.2514  MAPE=53.6436
[22:31:07] [comprehensive] combo 9/15 | BANKNIFTY/Close | decomp=decomposition+model model=XGBoost
[22:31:08] [comprehensive]    ✓ RMSE=22451.0182  MAE=22418.2857  MAPE=42.9936
[22:31:08] [comprehensive] combo 10/15 | BANKNIFTY/Close | decomp=decomposition+model model=RandomForest
[22:31:09] [comprehensive]    ✓ RMSE=22406.8536  MAE=22374.2394  MAPE=42.9090
[22:31:09] [comprehensive] combo 11/15 | BANKNIFTY/Close | decomp=hybrid model=ARIMA
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x3175a4af0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[22:32:02] [comprehensive]    ↳ No prediction produced — skipping
[22:32:02] [comprehensive] combo 12/15 | BANKNIFTY/Close | decomp=hybrid model=ExpSmoothing
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x31b5053f0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[22:32:56] [comprehensive]    ↳ No prediction produced — skipping
[22:32:56] [comprehensive] combo 13/15 | BANKNIFTY/Close | decomp=hybrid model=LSTM
[22:33:49] [comprehensive]    ↳ No prediction produced — skipping
[22:33:49] [comprehensive] combo 14/15 | BANKNIFTY/Close | decomp=hybrid model=XGBoost
[22:34:42] [comprehensive]    ↳ No prediction produced — skipping
[22:34:42] [comprehensive] combo 15/15 | BANKNIFTY/Close | decomp=hybrid model=RandomForest
[22:35:35] [comprehensive]    ↳ No prediction produced — skipping
[22:35:35] [comprehensive] Done. Total results: 10
[22:35:35] [advanced_dl] Starting: 1 stock(s), 1 target(s), 2 setup(s), 5 model(s)  →  up to 10 runs
[22:35:35] [advanced_dl] Models: ['BiLSTM', 'Transformer', 'AttentionForecaster', 'XGBoostSeq', 'Hybrid_ARIMA_BiLSTM_XGB']
[22:35:35] [advanced_dl] ── Stock: BANKNIFTY  (train=3647, test=30 rows)
[22:35:35] [advanced_dl]    Preparing data: target=Close, setup=univariate, lookback=20
[22:35:35] [advanced_dl]    Data ready: x_train=(3627, 20, 1), y_train=(3627,), x_test=(10, 20, 1), features=1
[22:35:35] [advanced_dl] combo 1/10 | BANKNIFTY/Close/univariate | model=BiLSTM  (epochs=12)
[22:35:40] [advanced_dl]    ✓ RMSE=827.3525  MAE=612.0739  MAPE=1.1942
[22:35:40] [advanced_dl] combo 2/10 | BANKNIFTY/Close/univariate | model=Transformer  (epochs=12)
[22:35:44] [advanced_dl]    ✓ RMSE=3750.8074  MAE=3699.7722  MAPE=7.1830
[22:35:44] [advanced_dl] combo 3/10 | BANKNIFTY/Close/univariate | model=AttentionForecaster  (epochs=12)
[22:35:52] [advanced_dl]    ✓ RMSE=7171.0682  MAE=7144.8846  MAPE=13.8845
[22:35:52] [advanced_dl] combo 4/10 | BANKNIFTY/Close/univariate | model=XGBoostSeq  (epochs=12)
[22:35:52] [advanced_dl]    ✓ RMSE=306.5170  MAE=263.8608  MAPE=0.5142
[22:35:52] [advanced_dl] combo 5/10 | BANKNIFTY/Close/univariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=12)
[22:36:03] [advanced_dl]    ✓ RMSE=5464.9761  MAE=5442.7719  MAPE=10.5896
[22:36:03] [advanced_dl]    Preparing data: target=Close, setup=multivariate, lookback=20
[22:36:03] [advanced_dl]    Data ready: x_train=(3627, 20, 7), y_train=(3627,), x_test=(10, 20, 7), features=7
[22:36:03] [advanced_dl] combo 6/10 | BANKNIFTY/Close/multivariate | model=BiLSTM  (epochs=14)
[22:36:09] [advanced_dl]    ✓ RMSE=885.7064  MAE=816.9168  MAPE=1.5876
[22:36:09] [advanced_dl] combo 7/10 | BANKNIFTY/Close/multivariate | model=Transformer  (epochs=14)
[22:36:14] [advanced_dl]    ✓ RMSE=4702.9508  MAE=4670.0066  MAPE=9.0717
[22:36:14] [advanced_dl] combo 8/10 | BANKNIFTY/Close/multivariate | model=AttentionForecaster  (epochs=14)
[22:36:22] [advanced_dl]    ✓ RMSE=1213.0050  MAE=1131.4717  MAPE=2.2078
[22:36:22] [advanced_dl] combo 9/10 | BANKNIFTY/Close/multivariate | model=XGBoostSeq  (epochs=14)
[22:36:23] [advanced_dl]    ✓ RMSE=399.2911  MAE=314.3946  MAPE=0.6136
[22:36:23] [advanced_dl] combo 10/10 | BANKNIFTY/Close/multivariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=14)
[22:36:37] [advanced_dl]    ✓ RMSE=7435.7499  MAE=7424.2027  MAPE=14.4436
[22:36:37] [advanced_dl] Done. Total results: 10
[22:36:37] INFO
──────────────────────────────────────────────────
[22:36:37] INFO     [2/5] Stock: HDFCBANK
[22:36:37] INFO     Item: HDFCBANK | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[22:36:37] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[22:37:12] INFO     [ OK ] autogluon_timeseries — 35.6s | RMSE=35.7272  MAE=29.9989
[22:37:12] INFO     [START] statsforecast
[22:37:17] INFO     [ OK ] statsforecast — 4.4s | RMSE=39.0596  MAE=33.8647
[22:37:17] INFO     [START] flaml
[22:38:20] INFO     [ OK ] flaml — 63.4s | RMSE=40.1270  MAE=35.2092
[22:38:20] INFO     Best backend: ag_ETS | RMSE=35.7272  MAE=29.9989
[22:38:20] INFO     forecast_last_horizon complete
[22:38:20] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/predictions/HDFCBANK_predictions_h30.csv
[22:38:20] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[22:38:20] [comprehensive] ── Stock: HDFCBANK  (train=3651, test=30 rows)
[22:38:20] [comprehensive] combo 1/15 | HDFCBANK/Close | decomp=original model=ARIMA
[22:38:21] [comprehensive]    ✓ RMSE=61.0544  MAE=57.0245  MAPE=6.3341
[22:38:21] [comprehensive] combo 2/15 | HDFCBANK/Close | decomp=original model=ExpSmoothing
[22:38:21] [comprehensive]    ✓ RMSE=58.0976  MAE=54.0149  MAPE=5.9980
[22:38:21] [comprehensive] combo 3/15 | HDFCBANK/Close | decomp=original model=LSTM
[22:40:29] [comprehensive]    ✓ RMSE=109.7486  MAE=108.0319  MAPE=12.0620
[22:40:29] [comprehensive] combo 4/15 | HDFCBANK/Close | decomp=original model=XGBoost
[22:40:29] [comprehensive]    ✓ RMSE=51.3174  MAE=46.7660  MAPE=5.1859
[22:40:29] [comprehensive] combo 5/15 | HDFCBANK/Close | decomp=original model=RandomForest
[22:40:30] [comprehensive]    ✓ RMSE=43.5573  MAE=38.6023  MAPE=4.2744
[22:40:30] [comprehensive] combo 6/15 | HDFCBANK/Close | decomp=decomposition+model model=ARIMA
[22:40:30] [comprehensive]    ✓ RMSE=434.8248  MAE=434.3024  MAPE=48.6402
[22:40:30] [comprehensive] combo 7/15 | HDFCBANK/Close | decomp=decomposition+model model=ExpSmoothing
[22:40:30] [comprehensive]    ✓ RMSE=434.1233  MAE=433.5992  MAPE=48.5615
[22:40:30] [comprehensive] combo 8/15 | HDFCBANK/Close | decomp=decomposition+model model=LSTM
[22:43:11] [comprehensive]    ✓ RMSE=474.4183  MAE=473.8306  MAPE=53.0663
[22:43:11] [comprehensive] combo 9/15 | HDFCBANK/Close | decomp=decomposition+model model=XGBoost
[22:43:11] [comprehensive]    ✓ RMSE=437.4854  MAE=436.7720  MAPE=48.9074
[22:43:11] [comprehensive] combo 10/15 | HDFCBANK/Close | decomp=decomposition+model model=RandomForest
[22:43:13] [comprehensive]    ✓ RMSE=436.3844  MAE=435.6670  MAPE=48.7835
[22:43:13] [comprehensive] combo 11/15 | HDFCBANK/Close | decomp=hybrid model=ARIMA
[22:44:22] [comprehensive]    ↳ No prediction produced — skipping
[22:44:22] [comprehensive] combo 12/15 | HDFCBANK/Close | decomp=hybrid model=ExpSmoothing
[22:45:31] [comprehensive]    ↳ No prediction produced — skipping
[22:45:31] [comprehensive] combo 13/15 | HDFCBANK/Close | decomp=hybrid model=LSTM
[22:46:39] [comprehensive]    ↳ No prediction produced — skipping
[22:46:39] [comprehensive] combo 14/15 | HDFCBANK/Close | decomp=hybrid model=XGBoost
[22:47:46] [comprehensive]    ↳ No prediction produced — skipping
[22:47:46] [comprehensive] combo 15/15 | HDFCBANK/Close | decomp=hybrid model=RandomForest
[22:48:54] [comprehensive]    ↳ No prediction produced — skipping
[22:48:54] [comprehensive] Done. Total results: 10
[22:48:54] [advanced_dl] Starting: 1 stock(s), 1 target(s), 2 setup(s), 5 model(s)  →  up to 10 runs
[22:48:54] [advanced_dl] Models: ['BiLSTM', 'Transformer', 'AttentionForecaster', 'XGBoostSeq', 'Hybrid_ARIMA_BiLSTM_XGB']
[22:48:54] [advanced_dl] ── Stock: HDFCBANK  (train=3651, test=30 rows)
[22:48:54] [advanced_dl]    Preparing data: target=Close, setup=univariate, lookback=20
[22:48:54] [advanced_dl]    Data ready: x_train=(3631, 20, 1), y_train=(3631,), x_test=(10, 20, 1), features=1
[22:48:54] [advanced_dl] combo 1/10 | HDFCBANK/Close/univariate | model=BiLSTM  (epochs=12)
[22:49:01] [advanced_dl]    ✓ RMSE=52.8370  MAE=52.3171  MAPE=5.9026
[22:49:01] [advanced_dl] combo 2/10 | HDFCBANK/Close/univariate | model=Transformer  (epochs=12)
[22:49:05] [advanced_dl]    ✓ RMSE=18.2145  MAE=15.5514  MAPE=1.7461
[22:49:05] [advanced_dl] combo 3/10 | HDFCBANK/Close/univariate | model=AttentionForecaster  (epochs=12)
[22:49:13] [advanced_dl]    ✓ RMSE=112.9646  MAE=112.5523  MAPE=12.7023
[22:49:13] [advanced_dl] combo 4/10 | HDFCBANK/Close/univariate | model=XGBoostSeq  (epochs=12)
[22:49:14] [advanced_dl]    ✓ RMSE=38.0764  MAE=37.0656  MAPE=4.1770
[22:49:14] [advanced_dl] combo 5/10 | HDFCBANK/Close/univariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=12)
[22:49:26] [advanced_dl]    ✓ RMSE=11.9984  MAE=10.6357  MAPE=1.2057
[22:49:26] [advanced_dl]    Preparing data: target=Close, setup=multivariate, lookback=20
[22:49:26] [advanced_dl]    Data ready: x_train=(3631, 20, 7), y_train=(3631,), x_test=(10, 20, 7), features=7
[22:49:26] [advanced_dl] combo 6/10 | HDFCBANK/Close/multivariate | model=BiLSTM  (epochs=14)
[22:49:39] [advanced_dl]    ✓ RMSE=67.7808  MAE=67.3759  MAPE=7.6042
[22:49:39] [advanced_dl] combo 7/10 | HDFCBANK/Close/multivariate | model=Transformer  (epochs=14)
[22:49:49] [advanced_dl]    ✓ RMSE=114.8517  MAE=114.5364  MAPE=12.9281
[22:49:49] [advanced_dl] combo 8/10 | HDFCBANK/Close/multivariate | model=AttentionForecaster  (epochs=14)
[22:50:10] [advanced_dl]    ✓ RMSE=51.2644  MAE=49.3839  MAPE=5.5635
[22:50:10] [advanced_dl] combo 9/10 | HDFCBANK/Close/multivariate | model=XGBoostSeq  (epochs=14)
[22:50:12] [advanced_dl]    ✓ RMSE=33.9891  MAE=32.7603  MAPE=3.6928
[22:50:12] [advanced_dl] combo 10/10 | HDFCBANK/Close/multivariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=14)
[22:50:31] [advanced_dl]    ✓ RMSE=8.4678  MAE=6.3483  MAPE=0.7154
[22:50:31] [advanced_dl] Done. Total results: 10
[22:50:31] INFO
──────────────────────────────────────────────────
[22:50:31] INFO     [3/5] Stock: NIFTY50
[22:50:31] INFO     Item: NIFTY50 | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[22:50:31] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[22:51:04] INFO     [ OK ] autogluon_timeseries — 33.4s | RMSE=591.1197  MAE=503.3350
[22:51:04] INFO     [START] statsforecast
[22:51:05] INFO     [ OK ] statsforecast — 0.6s | RMSE=751.3649  MAE=639.9137
[22:51:05] INFO     [START] flaml
[22:51:52] INFO     [ OK ] flaml — 47.1s | RMSE=2023.9641  MAE=1871.0581
[22:51:52] INFO     Best backend: ag_RecursiveTabular | RMSE=531.3590  MAE=469.4794
[22:51:52] INFO     forecast_last_horizon complete
[22:51:52] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/predictions/NIFTY50_predictions_h30.csv
[22:51:52] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[22:51:52] [comprehensive] ── Stock: NIFTY50  (train=3631, test=30 rows)
[22:51:52] [comprehensive] combo 1/15 | NIFTY50/Close | decomp=original model=ARIMA
[22:51:52] [comprehensive]    ✓ RMSE=731.3667  MAE=612.9407  MAPE=2.5124
[22:51:52] [comprehensive] combo 2/15 | NIFTY50/Close | decomp=original model=ExpSmoothing
[22:51:52] [comprehensive]    ✓ RMSE=670.5291  MAE=544.9889  MAPE=2.2317
[22:51:52] [comprehensive] combo 3/15 | NIFTY50/Close | decomp=original model=LSTM
[22:53:34] [comprehensive]    ✓ RMSE=39714.6827  MAE=37622.4785  MAPE=155.5280
[22:53:34] [comprehensive] combo 4/15 | NIFTY50/Close | decomp=original model=XGBoost
[22:53:35] [comprehensive]    ✓ RMSE=533.7538  MAE=439.8382  MAPE=1.8253
[22:53:35] [comprehensive] combo 5/15 | NIFTY50/Close | decomp=original model=RandomForest
[22:53:35] [comprehensive]    ✓ RMSE=683.1721  MAE=574.9105  MAPE=2.3680
[22:53:35] [comprehensive] combo 6/15 | NIFTY50/Close | decomp=decomposition+model model=ARIMA
[22:53:36] [comprehensive]    ✓ RMSE=9421.3711  MAE=9411.5643  MAPE=38.9890
[22:53:36] [comprehensive] combo 7/15 | NIFTY50/Close | decomp=decomposition+model model=ExpSmoothing
[22:53:36] [comprehensive]    ✓ RMSE=9405.5994  MAE=9395.5316  MAPE=38.9223
[22:53:36] [comprehensive] combo 8/15 | NIFTY50/Close | decomp=decomposition+model model=LSTM
[22:56:13] [comprehensive]    ✓ RMSE=12634.3564  MAE=12626.0398  MAPE=52.3141
[22:56:13] [comprehensive] combo 9/15 | NIFTY50/Close | decomp=decomposition+model model=XGBoost
[22:56:14] [comprehensive]    ✓ RMSE=9760.6536  MAE=9749.6258  MAPE=40.3883
[22:56:14] [comprehensive] combo 10/15 | NIFTY50/Close | decomp=decomposition+model model=RandomForest
[22:56:15] [comprehensive]    ✓ RMSE=9646.6346  MAE=9634.9457  MAPE=39.9123
[22:56:15] [comprehensive] combo 11/15 | NIFTY50/Close | decomp=hybrid model=ARIMA
[22:57:22] [comprehensive]    ↳ No prediction produced — skipping
[22:57:22] [comprehensive] combo 12/15 | NIFTY50/Close | decomp=hybrid model=ExpSmoothing
[23:15:19] [comprehensive]    ↳ No prediction produced — skipping
[23:15:19] [comprehensive] combo 13/15 | NIFTY50/Close | decomp=hybrid model=LSTM
[23:21:37] [comprehensive]    ↳ No prediction produced — skipping
[23:21:37] [comprehensive] combo 14/15 | NIFTY50/Close | decomp=hybrid model=XGBoost
[23:22:45] [comprehensive]    ↳ No prediction produced — skipping
[23:22:45] [comprehensive] combo 15/15 | NIFTY50/Close | decomp=hybrid model=RandomForest
[23:24:13] [comprehensive]    ↳ No prediction produced — skipping
[23:24:13] [comprehensive] Done. Total results: 10
[23:24:13] [advanced_dl] Starting: 1 stock(s), 1 target(s), 2 setup(s), 5 model(s)  →  up to 10 runs
[23:24:13] [advanced_dl] Models: ['BiLSTM', 'Transformer', 'AttentionForecaster', 'XGBoostSeq', 'Hybrid_ARIMA_BiLSTM_XGB']
[23:24:13] [advanced_dl] ── Stock: NIFTY50  (train=3631, test=30 rows)
[23:24:13] [advanced_dl]    Preparing data: target=Close, setup=univariate, lookback=20
[23:24:13] [advanced_dl]    Data ready: x_train=(3611, 20, 1), y_train=(3611,), x_test=(10, 20, 1), features=1
[23:24:13] [advanced_dl] combo 1/10 | NIFTY50/Close/univariate | model=BiLSTM  (epochs=12)
[23:24:20] [advanced_dl]    ✓ RMSE=841.6249  MAE=817.5777  MAPE=3.4232
[23:24:20] [advanced_dl] combo 2/10 | NIFTY50/Close/univariate | model=Transformer  (epochs=12)
[23:24:25] [advanced_dl]    ✓ RMSE=1980.1983  MAE=1965.5810  MAPE=8.2355
[23:24:25] [advanced_dl] combo 3/10 | NIFTY50/Close/univariate | model=AttentionForecaster  (epochs=12)
[23:24:34] [advanced_dl]    ✓ RMSE=3039.8534  MAE=3030.3801  MAPE=12.7023
[23:24:34] [advanced_dl] combo 4/10 | NIFTY50/Close/univariate | model=XGBoostSeq  (epochs=12)
[23:24:34] [advanced_dl]    ✓ RMSE=443.9727  MAE=431.9341  MAPE=1.8139
[23:24:34] [advanced_dl] combo 5/10 | NIFTY50/Close/univariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=12)
[23:24:47] [advanced_dl]    ✓ RMSE=236.5243  MAE=197.8762  MAPE=0.8270
[23:24:47] [advanced_dl]    Preparing data: target=Close, setup=multivariate, lookback=20
[23:24:47] [advanced_dl]    Data ready: x_train=(3611, 20, 7), y_train=(3611,), x_test=(10, 20, 7), features=7
[23:24:47] [advanced_dl] combo 6/10 | NIFTY50/Close/multivariate | model=BiLSTM  (epochs=14)
[23:24:54] [advanced_dl]    ✓ RMSE=1091.1146  MAE=1077.5549  MAPE=4.5143
[23:24:54] [advanced_dl] combo 7/10 | NIFTY50/Close/multivariate | model=Transformer  (epochs=14)
[23:25:00] [advanced_dl]    ✓ RMSE=6917.1045  MAE=6913.8915  MAPE=28.9945
[23:25:00] [advanced_dl] combo 8/10 | NIFTY50/Close/multivariate | model=AttentionForecaster  (epochs=14)
[23:25:09] [advanced_dl]    ✓ RMSE=2801.2273  MAE=2782.4683  MAPE=11.6591
[23:25:09] [advanced_dl] combo 9/10 | NIFTY50/Close/multivariate | model=XGBoostSeq  (epochs=14)
[23:25:10] [advanced_dl]    ✓ RMSE=386.2095  MAE=358.8561  MAPE=1.5093
[23:25:10] [advanced_dl] combo 10/10 | NIFTY50/Close/multivariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=14)
[23:25:26] [advanced_dl]    ✓ RMSE=4124.3977  MAE=4120.2393  MAPE=17.2909
[23:25:26] [advanced_dl] Done. Total results: 10
[23:25:26] INFO
──────────────────────────────────────────────────
[23:25:26] INFO     [4/5] Stock: RELIANCE
[23:25:27] INFO     Item: RELIANCE | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[23:25:27] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[23:25:53] INFO     [ OK ] autogluon_timeseries — 26.4s | RMSE=128.4279  MAE=121.5991
[23:25:53] INFO     [START] statsforecast
[23:25:54] INFO     [ OK ] statsforecast — 0.7s | RMSE=41.4155  MAE=35.9238
[23:25:54] INFO     [START] flaml
[23:26:44] INFO     [ OK ] flaml — 49.8s | RMSE=107.0994  MAE=102.2171
[23:26:44] INFO     Best backend: ag_RecursiveTabular | RMSE=34.5617  MAE=29.7812
[23:26:44] INFO     forecast_last_horizon complete
[23:26:44] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/predictions/RELIANCE_predictions_h30.csv
[23:26:44] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[23:26:44] [comprehensive] ── Stock: RELIANCE  (train=3651, test=30 rows)
[23:26:44] [comprehensive] combo 1/15 | RELIANCE/Close | decomp=original model=ARIMA
[23:26:44] [comprehensive]    ✓ RMSE=35.7106  MAE=30.4268  MAPE=2.4304
[23:26:44] [comprehensive] combo 2/15 | RELIANCE/Close | decomp=original model=ExpSmoothing
[23:26:44] [comprehensive]    ✓ RMSE=37.8790  MAE=31.7322  MAPE=2.5434
[23:26:44] [comprehensive] combo 3/15 | RELIANCE/Close | decomp=original model=LSTM
[23:28:25] [comprehensive]    ✓ RMSE=86.2327  MAE=77.3634  MAPE=6.0691
[23:28:25] [comprehensive] combo 4/15 | RELIANCE/Close | decomp=original model=XGBoost
[23:28:26] [comprehensive]    ✓ RMSE=57.4340  MAE=46.9203  MAPE=3.6599
[23:28:26] [comprehensive] combo 5/15 | RELIANCE/Close | decomp=original model=RandomForest
[23:28:26] [comprehensive]    ✓ RMSE=61.7045  MAE=50.3160  MAPE=3.9243
[23:28:26] [comprehensive] combo 6/15 | RELIANCE/Close | decomp=decomposition+model model=ARIMA
[23:28:27] [comprehensive]    ✓ RMSE=537.3108  MAE=536.2772  MAPE=42.5674
[23:28:27] [comprehensive] combo 7/15 | RELIANCE/Close | decomp=decomposition+model model=ExpSmoothing
[23:28:27] [comprehensive]    ✓ RMSE=539.3978  MAE=538.4308  MAPE=42.7414
[23:28:27] [comprehensive] combo 8/15 | RELIANCE/Close | decomp=decomposition+model model=LSTM
[23:31:06] [comprehensive]    ✓ RMSE=661.2853  MAE=660.3271  MAPE=52.4269
[23:31:06] [comprehensive] combo 9/15 | RELIANCE/Close | decomp=decomposition+model model=XGBoost
[23:31:07] [comprehensive]    ✓ RMSE=567.1373  MAE=566.0098  MAPE=44.9373
[23:31:07] [comprehensive] combo 10/15 | RELIANCE/Close | decomp=decomposition+model model=RandomForest
[23:31:08] [comprehensive]    ✓ RMSE=566.1776  MAE=564.9447  MAPE=44.8523
[23:31:08] [comprehensive] combo 11/15 | RELIANCE/Close | decomp=hybrid model=ARIMA
[23:32:16] [comprehensive]    ↳ No prediction produced — skipping
[23:32:16] [comprehensive] combo 12/15 | RELIANCE/Close | decomp=hybrid model=ExpSmoothing
[23:33:23] [comprehensive]    ↳ No prediction produced — skipping
[23:33:23] [comprehensive] combo 13/15 | RELIANCE/Close | decomp=hybrid model=LSTM
[23:34:31] [comprehensive]    ↳ No prediction produced — skipping
[23:34:31] [comprehensive] combo 14/15 | RELIANCE/Close | decomp=hybrid model=XGBoost
[23:35:38] [comprehensive]    ↳ No prediction produced — skipping
[23:35:38] [comprehensive] combo 15/15 | RELIANCE/Close | decomp=hybrid model=RandomForest
[23:36:59] [comprehensive]    ↳ No prediction produced — skipping
[23:36:59] [comprehensive] Done. Total results: 10
[23:36:59] [advanced_dl] Starting: 1 stock(s), 1 target(s), 2 setup(s), 5 model(s)  →  up to 10 runs
[23:36:59] [advanced_dl] Models: ['BiLSTM', 'Transformer', 'AttentionForecaster', 'XGBoostSeq', 'Hybrid_ARIMA_BiLSTM_XGB']
[23:36:59] [advanced_dl] ── Stock: RELIANCE  (train=3651, test=30 rows)
[23:36:59] [advanced_dl]    Preparing data: target=Close, setup=univariate, lookback=20
[23:36:59] [advanced_dl]    Data ready: x_train=(3631, 20, 1), y_train=(3631,), x_test=(10, 20, 1), features=1
[23:36:59] [advanced_dl] combo 1/10 | RELIANCE/Close/univariate | model=BiLSTM  (epochs=12)
[23:37:06] [advanced_dl]    ✓ RMSE=15.3769  MAE=11.7373  MAPE=0.9668
[23:37:06] [advanced_dl] combo 2/10 | RELIANCE/Close/univariate | model=Transformer  (epochs=12)
[23:37:11] [advanced_dl]    ✓ RMSE=22.2518  MAE=19.7247  MAPE=1.6265
[23:37:11] [advanced_dl] combo 3/10 | RELIANCE/Close/univariate | model=AttentionForecaster  (epochs=12)
[23:37:20] [advanced_dl]    ✓ RMSE=43.6754  MAE=41.7970  MAPE=3.4165
[23:37:20] [advanced_dl] combo 4/10 | RELIANCE/Close/univariate | model=XGBoostSeq  (epochs=12)
[23:37:21] [advanced_dl]    ✓ RMSE=18.2919  MAE=15.5724  MAPE=1.2749
[23:37:21] [advanced_dl] combo 5/10 | RELIANCE/Close/univariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=12)
[23:37:33] [advanced_dl]    ✓ RMSE=10.0961  MAE=7.0909  MAPE=0.5829
[23:37:33] [advanced_dl]    Preparing data: target=Close, setup=multivariate, lookback=20
[23:37:33] [advanced_dl]    Data ready: x_train=(3631, 20, 7), y_train=(3631,), x_test=(10, 20, 7), features=7
[23:37:33] [advanced_dl] combo 6/10 | RELIANCE/Close/multivariate | model=BiLSTM  (epochs=14)
[23:37:41] [advanced_dl]    ✓ RMSE=49.5621  MAE=48.6584  MAPE=3.9848
[23:37:41] [advanced_dl] combo 7/10 | RELIANCE/Close/multivariate | model=Transformer  (epochs=14)
[23:37:46] [advanced_dl]    ✓ RMSE=27.4508  MAE=25.0424  MAPE=2.0640
[23:37:46] [advanced_dl] combo 8/10 | RELIANCE/Close/multivariate | model=AttentionForecaster  (epochs=14)
[23:37:57] [advanced_dl]    ✓ RMSE=85.4504  MAE=84.0728  MAPE=6.9094
[23:37:57] [advanced_dl] combo 9/10 | RELIANCE/Close/multivariate | model=XGBoostSeq  (epochs=14)
[23:37:58] [advanced_dl]    ✓ RMSE=17.1166  MAE=14.5773  MAPE=1.1961
[23:37:58] [advanced_dl] combo 10/10 | RELIANCE/Close/multivariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=14)
[23:38:13] [advanced_dl]    ✓ RMSE=72.8564  MAE=72.2647  MAPE=5.9300
[23:38:13] [advanced_dl] Done. Total results: 10
[23:38:13] INFO
──────────────────────────────────────────────────
[23:38:13] INFO     [5/5] Stock: TCS
[23:38:13] INFO     Item: TCS | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[23:38:13] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[23:38:43] INFO     [ OK ] autogluon_timeseries — 29.6s | RMSE=234.1657  MAE=198.8693
[23:38:43] INFO     [START] statsforecast
[23:38:43] INFO     [ OK ] statsforecast — 0.6s | RMSE=259.7078  MAE=231.4619
[23:38:43] INFO     [START] flaml
[23:39:48] INFO     [ OK ] flaml — 64.5s | RMSE=255.1211  MAE=228.6933
[23:39:48] INFO     Best backend: ag_DirectTabular | RMSE=177.7365  MAE=140.8575
[23:39:48] INFO     forecast_last_horizon complete
[23:39:48] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/predictions/TCS_predictions_h30.csv
[23:39:48] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[23:39:48] [comprehensive] ── Stock: TCS  (train=3651, test=30 rows)
[23:39:48] [comprehensive] combo 1/15 | TCS/Close | decomp=original model=ARIMA
[23:39:48] [comprehensive]    ✓ RMSE=179.7535  MAE=150.9563  MAPE=3.6534
[23:39:48] [comprehensive] combo 2/15 | TCS/Close | decomp=original model=ExpSmoothing
[23:39:48] [comprehensive]    ✓ RMSE=169.1957  MAE=140.9284  MAPE=3.4113
[23:39:48] [comprehensive] combo 3/15 | TCS/Close | decomp=original model=LSTM
[23:41:30] [comprehensive]    ✓ RMSE=792.3345  MAE=780.3895  MAPE=19.1188
[23:41:30] [comprehensive] combo 4/15 | TCS/Close | decomp=original model=XGBoost
[23:41:31] [comprehensive]    ✓ RMSE=171.4181  MAE=139.3076  MAPE=3.4378
[23:41:31] [comprehensive] combo 5/15 | TCS/Close | decomp=original model=RandomForest
[23:41:32] [comprehensive]    ✓ RMSE=161.3581  MAE=130.4882  MAPE=3.2149
[23:41:32] [comprehensive] combo 6/15 | TCS/Close | decomp=decomposition+model model=ARIMA
[23:41:32] [comprehensive]    ✓ RMSE=1873.9656  MAE=1869.7593  MAPE=45.9628
[23:41:32] [comprehensive] combo 7/15 | TCS/Close | decomp=decomposition+model model=ExpSmoothing
[23:41:32] [comprehensive]    ✓ RMSE=1867.7465  MAE=1863.4421  MAPE=45.8066
[23:41:32] [comprehensive] combo 8/15 | TCS/Close | decomp=decomposition+model model=LSTM
[23:44:12] [comprehensive]    ✓ RMSE=2313.8615  MAE=2310.0209  MAPE=56.8024
[23:44:12] [comprehensive] combo 9/15 | TCS/Close | decomp=decomposition+model model=XGBoost
[23:44:12] [comprehensive]    ✓ RMSE=1948.7126  MAE=1944.3674  MAPE=47.7969
[23:44:12] [comprehensive] combo 10/15 | TCS/Close | decomp=decomposition+model model=RandomForest
[23:44:14] [comprehensive]    ✓ RMSE=1920.0690  MAE=1915.4029  MAPE=47.0808
[23:44:14] [comprehensive] combo 11/15 | TCS/Close | decomp=hybrid model=ARIMA
[23:45:22] [comprehensive]    ↳ No prediction produced — skipping
[23:45:22] [comprehensive] combo 12/15 | TCS/Close | decomp=hybrid model=ExpSmoothing
[23:46:30] [comprehensive]    ↳ No prediction produced — skipping
[23:46:30] [comprehensive] combo 13/15 | TCS/Close | decomp=hybrid model=LSTM
[23:47:52] [comprehensive]    ↳ No prediction produced — skipping
[23:47:52] [comprehensive] combo 14/15 | TCS/Close | decomp=hybrid model=XGBoost
[23:49:05] [comprehensive]    ↳ No prediction produced — skipping
[23:49:05] [comprehensive] combo 15/15 | TCS/Close | decomp=hybrid model=RandomForest
[23:50:14] [comprehensive]    ↳ No prediction produced — skipping
[23:50:14] [comprehensive] Done. Total results: 10
[23:50:14] [advanced_dl] Starting: 1 stock(s), 1 target(s), 2 setup(s), 5 model(s)  →  up to 10 runs
[23:50:14] [advanced_dl] Models: ['BiLSTM', 'Transformer', 'AttentionForecaster', 'XGBoostSeq', 'Hybrid_ARIMA_BiLSTM_XGB']
[23:50:14] [advanced_dl] ── Stock: TCS  (train=3651, test=30 rows)
[23:50:14] [advanced_dl]    Preparing data: target=Close, setup=univariate, lookback=20
[23:50:14] [advanced_dl]    Data ready: x_train=(3631, 20, 1), y_train=(3631,), x_test=(10, 20, 1), features=1
[23:50:14] [advanced_dl] combo 1/10 | TCS/Close/univariate | model=BiLSTM  (epochs=12)
[23:50:21] [advanced_dl]    ✓ RMSE=401.4812  MAE=397.4933  MAPE=9.9405
[23:50:21] [advanced_dl] combo 2/10 | TCS/Close/univariate | model=Transformer  (epochs=12)
[23:50:26] [advanced_dl]    ✓ RMSE=168.3603  MAE=150.5208  MAPE=3.7386
[23:50:26] [advanced_dl] combo 3/10 | TCS/Close/univariate | model=AttentionForecaster  (epochs=12)
[23:50:34] [advanced_dl]    ✓ RMSE=549.7060  MAE=544.5044  MAPE=13.6150
[23:50:34] [advanced_dl] combo 4/10 | TCS/Close/univariate | model=XGBoostSeq  (epochs=12)
[23:50:34] [advanced_dl]    ✓ RMSE=81.6808  MAE=70.5574  MAPE=1.7688
[23:50:34] [advanced_dl] combo 5/10 | TCS/Close/univariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=12)
[23:50:47] [advanced_dl]    ✓ RMSE=426.1928  MAE=423.6920  MAPE=10.6385
[23:50:47] [advanced_dl]    Preparing data: target=Close, setup=multivariate, lookback=20
[23:50:47] [advanced_dl]    Data ready: x_train=(3631, 20, 7), y_train=(3631,), x_test=(10, 20, 7), features=7
[23:50:47] [advanced_dl] combo 6/10 | TCS/Close/multivariate | model=BiLSTM  (epochs=14)
[23:50:56] [advanced_dl]    ✓ RMSE=107.0127  MAE=97.1356  MAPE=2.4186
[23:50:56] [advanced_dl] combo 7/10 | TCS/Close/multivariate | model=Transformer  (epochs=14)
[23:51:01] [advanced_dl]    ✓ RMSE=591.9001  MAE=585.1238  MAPE=14.6269
[23:51:01] [advanced_dl] combo 8/10 | TCS/Close/multivariate | model=AttentionForecaster  (epochs=14)
[23:51:11] [advanced_dl]    ✓ RMSE=419.4493  MAE=407.8927  MAPE=10.1804
[23:51:11] [advanced_dl] combo 9/10 | TCS/Close/multivariate | model=XGBoostSeq  (epochs=14)
[23:51:12] [advanced_dl]    ✓ RMSE=78.9214  MAE=61.7548  MAPE=1.5405
[23:51:12] [advanced_dl] combo 10/10 | TCS/Close/multivariate | model=Hybrid_ARIMA_BiLSTM_XGB  (epochs=14)
[23:51:27] [advanced_dl]    ✓ RMSE=61.4322  MAE=50.8625  MAPE=1.2822
[23:51:27] [advanced_dl] Done. Total results: 10
[23:51:27] INFO
fit_all_stocks() complete — 435 leaderboard rows across 5 stocks
BrainAutoMLForecast(target='Close', horizon=30, backends=True, comprehensive=True, advanced_dl=True, status=fitted)

In [4]:
# Full multi-stock leaderboard with all horizons
# Shows: stock, horizon, model, library, rmse, mae, mape

full_lb = model.multi_stock_leaderboard()
print(f"Total results: {len(full_lb)} (stocks × horizons × models)")
display(full_lb.head(20))

Total results: 435 (stocks × horizons × models)

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column,target
0,HDFCBANK,7,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,6.348257,NaN,8.467762,0.715394,NaN,NaN,NaN,NaN,NaN,Close
1,RELIANCE,7,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,7.090872,NaN,10.096055,0.582922,NaN,NaN,NaN,NaN,NaN,Close
2,HDFCBANK,7,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,10.635731,NaN,11.998385,1.205727,NaN,NaN,NaN,NaN,NaN,Close
3,RELIANCE,7,BiLSTM,dl_univariate,11.737322,NaN,15.376904,0.966799,NaN,NaN,NaN,NaN,NaN,Close
4,RELIANCE,7,XGBoostSeq,dl_multivariate,14.577267,NaN,17.116644,1.196149,NaN,NaN,NaN,NaN,NaN,Close
5,HDFCBANK,7,Transformer,dl_univariate,15.551426,NaN,18.214537,1.746103,NaN,NaN,NaN,NaN,NaN,Close
6,RELIANCE,7,XGBoostSeq,dl_univariate,15.572372,NaN,18.291878,1.274879,NaN,NaN,NaN,NaN,NaN,Close
7,HDFCBANK,7,WeightedEnsemble,autogluon_timeseries,14.083586,346.191452,18.606221,1.590334,1.612613,1.610910,1.570735,-0.990648,NaN,NaN
8,HDFCBANK,7,ETS,autogluon_internal,14.083586,346.191452,18.606221,1.590334,1.612613,1.610910,1.570735,-0.990648,NaN,NaN
9,HDFCBANK,7,arima,flaml,14.507630,361.167445,19.004406,1.638700,1.661879,1.659413,1.618028,-1.076762,NaN,NaN
10,HDFCBANK,7,AutoARIMA,statsforecast,14.759321,372.075636,19.289262,1.667274,1.691124,1.688202,1.646099,-1.139486,NaN,NaN
11,HDFCBANK,7,RecursiveTabular,autogluon_internal,16.194005,383.040541,19.571422,1.853992,1.830196,1.852304,1.806109,-1.202535,NaN,NaN
12,HDFCBANK,7,Naive,autogluon_internal,14.977888,391.644313,19.790005,1.691280,1.716537,1.713202,1.670476,-1.252008,NaN,NaN
13,HDFCBANK,7,Theta,autogluon_internal,15.941130,427.347091,20.672375,1.801224,1.828839,1.823379,1.777906,-1.457304,NaN,NaN
14,RELIANCE,7,Transformer,dl_univariate,19.724736,NaN,22.251812,1.626526,NaN,NaN,NaN,NaN,NaN,Close
15,RELIANCE,7,Transformer,dl_multivariate,25.042360,NaN,27.450828,2.064029,NaN,NaN,NaN,NaN,NaN,Close
16,RELIANCE,7,RecursiveTabular,autogluon_internal,23.056109,777.476697,27.883269,1.816966,1.831568,1.827333,1.563898,-0.083073,NaN,NaN
17,RELIANCE,7,SeasonalNaive,autogluon_internal,26.958383,1090.201269,33.018196,2.132982,2.144927,2.136611,1.828590,-0.518717,NaN,NaN
18,HDFCBANK,7,XGBoostSeq,dl_multivariate,32.760345,NaN,33.989149,3.692772,NaN,NaN,NaN,NaN,NaN,Close
19,RELIANCE,7,ETS,autogluon_internal,31.785518,1239.119103,35.201124,2.497204,2.531167,2.519190,2.156015,-0.726169,NaN,NaN

In [5]:
# Setup output directory for saving results
from datetime import datetime

output_dir = Path("brain_automl_output") / "metrics"
output_dir.mkdir(parents=True, exist_ok=True)
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

print(f"📁 Results will be saved to: {output_dir.absolute()}")

📁 Results will be saved to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/metrics

In [6]:
# Best model per stock for each horizon
best_per_stock = model.best_model_per_stock()
print("Best model for each stock × horizon:")
display(best_per_stock)

Best model for each stock × horizon:

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column,target
0,BANKNIFTY,7,XGBoostSeq,dl_univariate,263.860754,1.038494e+06,306.516984,0.514165,1.433224,1.428263,1.394982,-0.735316,Close,Close
1,BANKNIFTY,15,XGBoostSeq,dl_univariate,263.860754,1.489742e+06,306.516984,0.514165,1.940851,1.933704,1.918203,-0.424435,Close,Close
2,BANKNIFTY,30,XGBoostSeq,dl_univariate,263.860754,1.123803e+06,306.516984,0.514165,1.626499,1.627388,1.608469,-0.026795,Close,Close
3,HDFCBANK,7,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,6.348257,3.461915e+02,8.467762,0.715394,1.612613,1.610910,1.570735,-0.990648,Close,Close
4,HDFCBANK,15,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,6.348257,2.888586e+02,8.467762,0.715394,1.563255,1.566206,1.559868,0.410659,Close,Close
5,HDFCBANK,30,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,6.348257,1.276433e+03,8.467762,0.715394,3.389339,3.356297,3.345764,-2.284864,Close,Close
6,NIFTY50,7,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,197.876156,2.096093e+05,236.524250,0.826977,1.743643,1.737964,2.319736,-0.724712,Close,Close
7,NIFTY50,15,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,197.876156,3.123310e+05,236.524250,0.826977,2.187394,2.173471,2.939470,-0.906517,Close,Close
8,NIFTY50,30,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,197.876156,2.823424e+05,236.524250,0.826977,1.952687,1.945308,2.621952,-0.614008,Close,Close
9,RELIANCE,7,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,7.090872,7.774767e+02,10.096055,0.582922,1.831568,1.827333,1.563898,-0.083073,Close,Close
10,RELIANCE,15,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,7.090872,1.807581e+03,10.096055,0.582922,2.942657,2.917298,2.537858,-1.250977,Close,Close
11,RELIANCE,30,Hybrid_ARIMA_BiLSTM_XGB,dl_univariate,7.090872,1.194508e+03,10.096055,0.582922,2.368769,2.369290,2.020062,0.106816,Close,Close
12,TCS,7,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,50.862473,3.341118e+04,61.432179,1.282156,4.057346,4.009102,4.273479,-1.945522,Close,Close
13,TCS,15,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,50.862473,2.558522e+04,61.432179,1.282156,2.771030,2.776648,3.013320,-0.995928,Close,Close
14,TCS,30,Hybrid_ARIMA_BiLSTM_XGB,dl_multivariate,50.862473,3.159025e+04,61.432179,1.282156,3.440765,3.461854,3.738671,-1.279274,Close,Close

In [7]:
# Overall best models across all stocks (by mean RMSE)
overall_best = model.overall_best_models(top_n=10)
print("Top 10 models by mean RMSE across all stocks:")
display(overall_best)

Top 10 models by mean RMSE across all stocks:

,model,library,horizon,mean_rmse,std_rmse,n_stocks
0,XGBoostSeq,dl_univariate,7,177.707764,188.162390,5
1,XGBoostSeq,dl_multivariate,7,183.105569,192.762670,5
2,RecursiveTabular,autogluon_internal,7,370.749666,461.934261,5
3,AutoARIMA,statsforecast,7,384.146093,465.536830,5
4,ETS,autogluon_internal,7,387.004702,482.561149,5
5,Naive,autogluon_internal,7,392.596696,482.918611,5
6,Theta,autogluon_internal,7,407.135873,504.110767,5
7,BiLSTM,dl_univariate,7,427.734484,400.710599,5
8,BiLSTM,dl_multivariate,7,440.235322,506.081385,5
9,DirectTabular,autogluon_internal,7,445.443958,424.255300,5
10,XGBoostSeq,dl_univariate,15,177.707764,188.162390,5
11,XGBoostSeq,dl_multivariate,15,183.105569,192.762670,5
12,BiLSTM,dl_univariate,15,427.734484,400.710599,5
13,DirectTabular,autogluon_internal,15,432.917054,481.119536,5
14,BiLSTM,dl_multivariate,15,440.235322,506.081385,5
15,original/XGBoost,classical,15,490.459098,671.141231,5
16,original/RandomForest,classical,15,503.520208,649.774502,5
17,RecursiveTabular,autogluon_internal,15,532.770131,732.922948,5
18,original/ExpSmoothing,classical,15,598.897553,855.607467,5
19,WeightedEnsemble,autogluon_timeseries,15,603.219451,838.498302,5
20,XGBoostSeq,dl_univariate,30,177.707764,188.162390,5
21,XGBoostSeq,dl_multivariate,30,183.105569,192.762670,5
22,DirectTabular,autogluon_internal,30,416.730984,408.941157,5
23,BiLSTM,dl_univariate,30,427.734484,400.710599,5
24,BiLSTM,dl_multivariate,30,440.235322,506.081385,5
25,original/XGBoost,classical,30,490.459098,671.141231,5
26,RecursiveTabular,autogluon_internal,30,491.016912,658.782293,5
27,original/RandomForest,classical,30,503.520208,649.774502,5
28,ETS,autogluon_internal,30,568.616378,754.533011,5
29,AutoARIMA,statsforecast,30,575.302784,735.947657,5

In [8]:
# Horizon degradation analysis: how does RMSE change with horizon length?
# Average RMSE across all stocks for each horizon

horizon_perf = (
    full_lb.groupby(["horizon", "model", "library"])["rmse"]
    .mean()
    .reset_index()
    .sort_values("rmse")
)

# Top 5 models per horizon
top_models = []
for h in [7, 15, 30]:
    top_models.extend(
        horizon_perf[horizon_perf["horizon"] == h].head(5)["model"].tolist()
    )
top_models = list(set(top_models))

fig = px.line(
    horizon_perf[horizon_perf["model"].isin(top_models)],
    x="horizon",
    y="rmse",
    color="model",
    markers=True,
    title="Forecast Degradation: RMSE vs Horizon Length (Top Models)",
    labels={"rmse": "Mean RMSE", "horizon": "Horizon (days)"},
)
fig.show()

# Save plot as interactive HTML
plot_path = output_dir / f"horizon_degradation_plot_{timestamp}.html"
fig.write_html(plot_path)
print(f"✅ Saved horizon degradation plot to: {plot_path}")

✅ Saved horizon degradation plot to: brain_automl_output/metrics/horizon_degradation_plot_20260406_235127.html

In [9]:
# Visualize RMSE by stock and horizon

# Best model per stock-horizon combination
viz_data = best_per_stock.copy()

fig = px.bar(
    viz_data,
    x="stock",
    y="rmse",
    color="horizon",
    barmode="group",
    title="Best Model RMSE by Stock and Horizon",
    labels={"rmse": "RMSE", "stock": "Stock", "horizon": "Horizon (days)"},
    hover_data=["model", "library", "mae", "mape"],
)
fig.show()

# Save plot as interactive HTML
plot_path = output_dir / f"stock_horizon_rmse_plot_{timestamp}.html"
fig.write_html(plot_path)
print(f"✅ Saved stock×horizon RMSE plot to: {plot_path}")

✅ Saved stock×horizon RMSE plot to: brain_automl_output/metrics/stock_horizon_rmse_plot_20260406_235127.html

In [10]:
# Save all performance metrics to CSV files

# Save full leaderboard
full_lb_path = output_dir / f"full_leaderboard_{timestamp}.csv"
full_lb.to_csv(full_lb_path, index=False)
print(f"✅ Saved full leaderboard ({len(full_lb)} rows) to: {full_lb_path}")

# Save best per stock
best_per_stock_path = output_dir / f"best_per_stock_{timestamp}.csv"
best_per_stock.to_csv(best_per_stock_path, index=False)
print(f"✅ Saved best-per-stock results to: {best_per_stock_path}")

# Save overall best
overall_best_path = output_dir / f"overall_best_models_{timestamp}.csv"
overall_best.to_csv(overall_best_path, index=False)
print(f"✅ Saved overall best models to: {overall_best_path}")

# Save horizon performance analysis
horizon_perf_path = output_dir / f"horizon_degradation_{timestamp}.csv"
horizon_perf.to_csv(horizon_perf_path, index=False)
print(f"✅ Saved horizon degradation analysis to: {horizon_perf_path}")

print(f"📁 All metrics saved to: {output_dir.absolute()}")

✅ Saved full leaderboard (435 rows) to: brain_automl_output/metrics/full_leaderboard_20260406_235127.csv
✅ Saved best-per-stock results to: brain_automl_output/metrics/best_per_stock_20260406_235127.csv
✅ Saved overall best models to: brain_automl_output/metrics/overall_best_models_20260406_235127.csv
✅ Saved horizon degradation analysis to: brain_automl_output/metrics/horizon_degradation_20260406_235127.csv
📁 All metrics saved to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/metrics

In [11]:
# Summary of all saved files
print("\n" + "="*70)
print("📊 PERFORMANCE METRICS SAVED")
print("="*70)
print(f"\n📁 Output directory: {output_dir.absolute()}\n")
print("CSV Files:")
print(f"  • Full leaderboard: {full_lb_path.name}")
print(f"  • Best per stock: {best_per_stock_path.name}")
print(f"  • Overall best models: {overall_best_path.name}")
print(f"  • Horizon degradation: {horizon_perf_path.name}")
print(f"\nHTML Visualizations:")
print(f"  • Horizon degradation plot: horizon_degradation_plot_{timestamp}.html")
print(f"  • Stock×Horizon RMSE plot: stock_horizon_rmse_plot_{timestamp}.html")
print("\n" + "="*70)

======================================================================
📊 PERFORMANCE METRICS SAVED
======================================================================

📁 Output directory: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/metrics

CSV Files:
  • Full leaderboard: full_leaderboard_20260406_235127.csv
  • Best per stock: best_per_stock_20260406_235127.csv
  • Overall best models: overall_best_models_20260406_235127.csv
  • Horizon degradation: horizon_degradation_20260406_235127.csv

HTML Visualizations:
  • Horizon degradation plot: horizon_degradation_plot_20260406_235127.html
  • Stock×Horizon RMSE plot: stock_horizon_rmse_plot_20260406_235127.html

======================================================================

In [13]:
# ─────────────────────────────────────────────────────────────────────────────
# STANDALONE: Load saved metrics and reproduce all charts after kernel restart
# (Filter to Close target/column only — Volatility analysis moved to a separate notebook)
# ─────────────────────────────────────────────────────────────────────────────
from pathlib import Path
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# ── Point at the saved run ────────────────────────────────────────────────────
METRICS_DIR = Path("brain_automl_output/metrics")
RUN_TS = "20260406_235127"   # ← change if you have a newer run

full_lb = pd.read_csv(METRICS_DIR / f"full_leaderboard_{RUN_TS}.csv")
# Keep only rows related to Close (remove Volatility targets)
if 'column' in full_lb.columns:
    full_lb = full_lb[full_lb['column'].astype(str).str.lower() == 'close'].reset_index(drop=True)

# Recompute derived tables from filtered leaderboard
best_per_stock = (
    full_lb.sort_values(['stock', 'horizon', 'rmse']).
    groupby(['stock', 'horizon'], as_index=False).first()
)

overall_best = (
    full_lb.groupby('model', as_index=False)['rmse']
    .mean()
    .sort_values('rmse')
    .head(10)
)

horizon_perf = (
    full_lb.groupby(['horizon','model','library'], as_index=False)['rmse']
    .mean()
)

print(f"✅ Loaded {len(full_lb):,} leaderboard rows (Close only) | "
      f"{full_lb['stock'].nunique()} stocks | "
      f"horizons: {sorted(full_lb['horizon'].unique().tolist())}")

# ── 1. Full leaderboard ───────────────────────────────────────────────────────
print("\n── Full Leaderboard (top 20) — Close only ──")
display(full_lb.head(20))

# ── 2. Best model per stock × horizon ────────────────────────────────────────
print("\n── Best Model per Stock × Horizon (Close only) ──")
display(best_per_stock)

# ── 3. Overall best models ────────────────────────────────────────────────────
print("\n── Overall Best Models (mean RMSE across all stocks) — Close only ──")
display(overall_best)

# ── Publication-ready comparison table ───────────────────────────────────────
# Compute per-model statistics across stocks
pub_tbl = (
    full_lb.groupby(["model", "library"]).agg(
        mean_rmse=("rmse", "mean"),
        std_rmse=("rmse", "std"),
        mean_mae=("mae", "mean"),
        mean_mape=("mape", "mean"),
        n_rows=("stock", "count"),
        n_stocks=("stock", lambda s: s.nunique()),
    ).reset_index()
)

# Compute median rank of each model across stocks for RMSE (lower is better)
ranks = []
for s in sorted(full_lb['stock'].unique()):
    df_s = full_lb[full_lb['stock'] == s].copy()
    df_s = df_s.dropna(subset=['rmse'])
    df_s['rank'] = df_s.groupby('horizon')['rmse'].rank(method='min')
    ranks.append(df_s[['model', 'rank', 'stock']])
if ranks:
    rank_df = pd.concat(ranks, ignore_index=True)
    median_rank = rank_df.groupby('model')['rank'].median().reset_index().rename(columns={'rank': 'median_rank'})
    pub_tbl = pub_tbl.merge(median_rank, on='model', how='left')

pub_tbl = pub_tbl.sort_values(['mean_rmse', 'median_rank']).reset_index(drop=True)

print('\n── Publication Table (top 20 models) ──')
display(pub_tbl.head(20))

# ── 4. RMSE bar chart — best model per stock and horizon ─────────────────────
fig = px.bar(
    best_per_stock,
    x="stock",
    y="rmse",
    color="horizon",
    barmode="group",
    text="model",
    title="Best Model RMSE by Stock and Horizon (Close only)",
    labels={"rmse": "RMSE", "stock": "Stock", "horizon": "Horizon (days)"},
    hover_data=["model", "library", "mae", "mape"],
)
fig.update_traces(textposition="outside", textfont_size=9)
fig.show()

# ── 5. Horizon degradation — RMSE vs horizon length (top models) ─────────────
top_models = []
for h in [7, 15, 30]:
    top_models.extend(
        horizon_perf[horizon_perf["horizon"] == h]
        .sort_values("rmse")
        .head(5)["model"]
        .tolist()
    )
top_models = list(dict.fromkeys(top_models))  # deduplicate, preserve order

fig2 = px.line(
    horizon_perf[horizon_perf["model"].isin(top_models)].sort_values(["model", "horizon"]),
    x="horizon",
    y="rmse",
    color="model",
    markers=True,
    title="Forecast Degradation: Mean RMSE vs Horizon Length (Top Models) — Close only",
    labels={"rmse": "Mean RMSE", "horizon": "Horizon (days)"},
)
fig2.update_xaxes(tickvals=[7, 15, 30])
fig2.show()

# ── 6. Heatmap — RMSE by stock × model at each horizon ───────────────────────
for h in [7, 15, 30]:
    lb_h = full_lb[full_lb["horizon"] == h].copy()
    if lb_h.empty:
        continue
    pivot = lb_h.pivot_table(index="model", columns="stock", values="rmse", aggfunc="min")
    # Keep top 15 models by mean RMSE
    pivot = pivot.loc[pivot.mean(axis=1).sort_values().head(15).index]

    fig3 = px.imshow(
        pivot,
        color_continuous_scale="RdYlGn_r",
        title=f"RMSE Heatmap — Horizon {h}d (Close only)",
        labels=dict(x="Stock", y="Model", color="RMSE"),
        aspect="auto",
    )
    fig3.update_layout(height=450, margin=dict(l=180))
    fig3.show()

print("\n✅ All charts rendered from saved metrics (Close only).")
print("ℹ️  Volatility-specific analysis has been moved to examples/volatility_checking.ipynb")

✅ Loaded 150 leaderboard rows (Close only) | 5 stocks | horizons: [7, 15, 30]

── Full Leaderboard (top 20) — Close only ──

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column,target
0,RELIANCE,7,original/ARIMA,classical,30.426803,NaN,35.710642,2.430413,NaN,NaN,NaN,NaN,Close,NaN
1,RELIANCE,7,original/ExpSmoothing,classical,31.732232,NaN,37.878985,2.543427,NaN,NaN,NaN,NaN,Close,NaN
2,HDFCBANK,7,original/RandomForest,classical,38.602265,NaN,43.557318,4.274445,NaN,NaN,NaN,NaN,Close,NaN
3,HDFCBANK,7,original/XGBoost,classical,46.765979,NaN,51.317378,5.185904,NaN,NaN,NaN,NaN,Close,NaN
4,RELIANCE,7,original/XGBoost,classical,46.920298,NaN,57.434004,3.659946,NaN,NaN,NaN,NaN,Close,NaN
5,HDFCBANK,7,original/ExpSmoothing,classical,54.014857,NaN,58.097584,5.998009,NaN,NaN,NaN,NaN,Close,NaN
6,HDFCBANK,7,original/ARIMA,classical,57.024482,NaN,61.054448,6.334070,NaN,NaN,NaN,NaN,Close,NaN
7,RELIANCE,7,original/RandomForest,classical,50.316026,NaN,61.704480,3.924320,NaN,NaN,NaN,NaN,Close,NaN
8,RELIANCE,7,original/LSTM,classical,77.363375,NaN,86.232685,6.069063,NaN,NaN,NaN,NaN,Close,NaN
9,HDFCBANK,7,original/LSTM,classical,108.031889,NaN,109.748626,12.062002,NaN,NaN,NaN,NaN,Close,NaN
10,TCS,7,original/RandomForest,classical,130.488190,NaN,161.358053,3.214869,NaN,NaN,NaN,NaN,Close,NaN
11,TCS,7,original/ExpSmoothing,classical,140.928429,NaN,169.195722,3.411293,NaN,NaN,NaN,NaN,Close,NaN
12,TCS,7,original/XGBoost,classical,139.307643,NaN,171.418135,3.437765,NaN,NaN,NaN,NaN,Close,NaN
13,TCS,7,original/ARIMA,classical,150.956342,NaN,179.753487,3.653372,NaN,NaN,NaN,NaN,Close,NaN
14,HDFCBANK,7,decomposition+model/ExpSmoothing,classical,433.599197,NaN,434.123266,48.561506,NaN,NaN,NaN,NaN,Close,NaN
15,HDFCBANK,7,decomposition+model/ARIMA,classical,434.302378,NaN,434.824849,48.640227,NaN,NaN,NaN,NaN,Close,NaN
16,HDFCBANK,7,decomposition+model/RandomForest,classical,435.666983,NaN,436.384362,48.783462,NaN,NaN,NaN,NaN,Close,NaN
17,HDFCBANK,7,decomposition+model/XGBoost,classical,436.771972,NaN,437.485360,48.907422,NaN,NaN,NaN,NaN,Close,NaN
18,HDFCBANK,7,decomposition+model/LSTM,classical,473.830578,NaN,474.418346,53.066291,NaN,NaN,NaN,NaN,Close,NaN
19,NIFTY50,7,original/XGBoost,classical,439.838150,NaN,533.753788,1.825338,NaN,NaN,NaN,NaN,Close,NaN

── Best Model per Stock × Horizon (Close only) ──

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column,target
0,BANKNIFTY,7,original/RandomForest,classical,1270.164705,NaN,1567.809116,2.418825,NaN,NaN,NaN,NaN,Close,None
1,BANKNIFTY,15,original/RandomForest,classical,1270.164705,NaN,1567.809116,2.418825,NaN,NaN,NaN,NaN,Close,None
2,BANKNIFTY,30,original/RandomForest,classical,1270.164705,NaN,1567.809116,2.418825,NaN,NaN,NaN,NaN,Close,None
3,HDFCBANK,7,original/RandomForest,classical,38.602265,NaN,43.557318,4.274445,NaN,NaN,NaN,NaN,Close,None
4,HDFCBANK,15,original/RandomForest,classical,38.602265,NaN,43.557318,4.274445,NaN,NaN,NaN,NaN,Close,None
5,HDFCBANK,30,original/RandomForest,classical,38.602265,NaN,43.557318,4.274445,NaN,NaN,NaN,NaN,Close,None
6,NIFTY50,7,original/XGBoost,classical,439.838150,NaN,533.753788,1.825338,NaN,NaN,NaN,NaN,Close,None
7,NIFTY50,15,original/XGBoost,classical,439.838150,NaN,533.753788,1.825338,NaN,NaN,NaN,NaN,Close,None
8,NIFTY50,30,original/XGBoost,classical,439.838150,NaN,533.753788,1.825338,NaN,NaN,NaN,NaN,Close,None
9,RELIANCE,7,original/ARIMA,classical,30.426803,NaN,35.710642,2.430413,NaN,NaN,NaN,NaN,Close,None
10,RELIANCE,15,original/ARIMA,classical,30.426803,NaN,35.710642,2.430413,NaN,NaN,NaN,NaN,Close,None
11,RELIANCE,30,original/ARIMA,classical,30.426803,NaN,35.710642,2.430413,NaN,NaN,NaN,NaN,Close,None
12,TCS,7,original/RandomForest,classical,130.488190,NaN,161.358053,3.214869,NaN,NaN,NaN,NaN,Close,None
13,TCS,15,original/RandomForest,classical,130.488190,NaN,161.358053,3.214869,NaN,NaN,NaN,NaN,Close,None
14,TCS,30,original/RandomForest,classical,130.488190,NaN,161.358053,3.214869,NaN,NaN,NaN,NaN,Close,None

── Overall Best Models (mean RMSE across all stocks) — Close only ──

                              model         rmse
9                  original/XGBoost   490.459098
8             original/RandomForest   503.520208
6             original/ExpSmoothing   598.897553
5                    original/ARIMA   642.728216
1  decomposition+model/ExpSmoothing  6972.040521
0         decomposition+model/ARIMA  6977.781852
3  decomposition+model/RandomForest  6995.223835
4       decomposition+model/XGBoost  7033.001415
2          decomposition+model/LSTM  8814.909583
7                     original/LSTM  9458.892466

── Publication Table (top 20 models) ──

,model,library,mean_rmse,std_rmse,mean_mae,mean_mape,n_rows,n_stocks,median_rank
0,original/XGBoost,classical,490.459098,621.356041,403.892831,3.333585,15,5,2.0
1,original/RandomForest,classical,503.520208,601.574294,412.896337,3.240093,15,5,1.0
2,original/ExpSmoothing,classical,598.897553,792.138591,504.844031,3.501296,15,5,2.0
3,original/ARIMA,classical,642.728216,850.051122,555.459523,3.717047,15,5,4.0
4,decomposition+model/ExpSmoothing,classical,6972.040521,8792.237556,6963.744332,43.871009,15,5,6.0
5,decomposition+model/ARIMA,classical,6977.781852,8795.704711,6969.564213,43.899689,15,5,7.0
6,decomposition+model/RandomForest,classical,6995.223835,8717.673179,6985.039926,44.707581,15,5,8.0
7,decomposition+model/XGBoost,classical,7033.001415,8738.014881,7023.012136,45.004694,15,5,9.0
8,decomposition+model/LSTM,classical,8814.909583,10960.369781,8807.093945,53.650666,15,5,10.0
9,original/LSTM,classical,9458.892466,15860.986243,9012.343317,41.031526,15,5,5.0

✅ All charts rendered from saved metrics (Close only).
ℹ️  Volatility-specific analysis has been moved to examples/volatility_checking.ipynb