# Volatility Forecasting Full Run
This notebook is a standalone end-to-end workflow that:
- installs required packages (`arch`, `statsforecast`, `flaml`, and optional `autogluon.timeseries`)
- loads stock data and builds `Volatility` as target if needed
- runs `BrainAutoMLForecast` using `brain_automl`
- runs volatility baselines per stock: EWMA(0.94), GARCH, EGARCH, and GJR-GARCH
- saves all outputs to `examples/volatility_output` (metrics, forecasts, plots, summaries)

Run cells top-to-bottom once.

In [1]:
from pathlib import Path
import os
import sys
import subprocess
import warnings

warnings.filterwarnings("ignore")

CWD = Path.cwd()
# Handle both possible launch roots: project root or examples folder
if (CWD / "src").exists():
    PROJECT_ROOT = CWD
elif (CWD.parent / "src").exists():
    PROJECT_ROOT = CWD.parent
else:
    PROJECT_ROOT = CWD

candidate_data = [
    PROJECT_ROOT / "examples" / "dataset.csv",
    PROJECT_ROOT / "dataset.csv",
    CWD / "dataset.csv",
]
DATA_PATH = next((p for p in candidate_data if p.exists()), candidate_data[0])

OUTPUT_DIR = PROJECT_ROOT / "examples" / "volatility_output"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("CWD:", CWD)
print("Project root:", PROJECT_ROOT)
print("Data path:", DATA_PATH)
print("Output path:", OUTPUT_DIR)

# Ensure src is importable
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

def pip_install(packages):
    if not packages:
        return
    cmd = [sys.executable, "-m", "pip", "install", *packages]
    print("Installing:", " ".join(packages))
    subprocess.check_call(cmd)

# Required for volatility models/backends
required_pkgs = ["arch", "statsforecast", "flaml", "seaborn", "plotly"]
try:
    pip_install(required_pkgs)
    print("Required packages installed.")
except Exception as e:
    print("Package installation issue:", e)
    print("Continuing with available packages.")

# Optional heavy package for richer backend coverage in some setups
INSTALL_AUTOGLUON = False  # set True if you want to attempt AutoGluon install
if INSTALL_AUTOGLUON:
    try:
        pip_install(["autogluon.timeseries"])
        print("AutoGluon installed.")
    except Exception as e:
        print("AutoGluon install failed:", e)
        print("Proceeding without AutoGluon.")

CWD: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples
Project root: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai
Data path: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/dataset.csv
Output path: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output
Installing: arch statsforecast flaml seaborn plotly
Requirement already satisfied: arch in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (8.0.0)
Requirement already satisfied: statsforecast in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (1.7.8)
Requirement already satisfied: flaml in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (2.5.0)
Requirement already satisfied: seaborn in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: plotly in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (5.24.1)
Requirement already satisfied: numpy<3,>=1.22.3 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from arch) (1.26.4)
Requirement already satisfied: pandas>=1.4.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from arch) (2.2.3)
Requirement already satisfied: scipy>=1.8 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from arch) (1.13.1)
Requirement already satisfied: statsmodels>=0.13.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from arch) (0.14.6)
Requirement already satisfied: packaging in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from arch) (26.0)
Requirement already satisfied: cloudpickle in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (3.1.2)
Requirement already satisfied: coreforecast>=0.0.12 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (0.0.16)
Requirement already satisfied: numba>=0.55.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (0.65.0)
Requirement already satisfied: tqdm in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (4.67.3)
Requirement already satisfied: fugue>=0.8.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (0.9.7)
Requirement already satisfied: utilsforecast>=0.1.4 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (0.2.11)
Requirement already satisfied: threadpoolctl>=3 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsforecast) (3.6.0)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from seaborn) (3.9.4)
Requirement already satisfied: tenacity>=6.2.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from plotly) (9.1.4)
Requirement already satisfied: triad>=1.0.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from fugue>=0.8.1->statsforecast) (1.0.2)
Requirement already satisfied: adagio>=0.2.6 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from fugue>=0.8.1->statsforecast) (0.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from pandas>=1.4.0->arch) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from pandas>=1.4.0->arch) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from pandas>=1.4.0->arch) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: pillow>=8 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: llvmlite<0.48,>=0.47.0dev0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from numba>=0.55.0->statsforecast) (0.47.0)
Requirement already satisfied: six>=1.5 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->arch) (1.17.0)
Requirement already satisfied: patsy>=0.5.6 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from statsmodels>=0.13.0->arch) (1.0.2)
Requirement already satisfied: pyarrow>=6.0.1 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from triad>=1.0.1->fugue>=0.8.1->statsforecast) (19.0.1)
Requirement already satisfied: fsspec>=2022.5.0 in /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/.venv/lib/python3.10/site-packages (from triad>=1.0.1->fugue>=0.8.1->statsforecast) (2024.6.1)
Required packages installed.

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv(DATA_PATH)
df.columns = [c.strip() for c in df.columns]

required_cols = {"Date", "Stock", "Close"}
missing = required_cols - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns: {sorted(missing)}")

df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df = df.dropna(subset=["Date", "Stock", "Close"]).copy()
df = df.sort_values(["Stock", "Date"]).reset_index(drop=True)

# Build volatility if missing (squared log returns)
if "Volatility" not in df.columns:
    df["_logret"] = np.log(df["Close"] / df.groupby("Stock")["Close"].shift(1))
    df["Volatility"] = (df["_logret"] ** 2).fillna(0.0)
    df = df.drop(columns=["_logret"])
else:
    if df["Volatility"].isna().any():
        df["_logret"] = np.log(df["Close"] / df.groupby("Stock")["Close"].shift(1))
        df["Volatility"] = df["Volatility"].fillna((df["_logret"] ** 2))
        df["Volatility"] = df["Volatility"].fillna(0.0)
        df = df.drop(columns=["_logret"])


print("Prepared data shape:", df.shape)
print("Stocks:", df["Stock"].nunique())
display(df.head())

df.to_csv(OUTPUT_DIR / "dataset_with_volatility.csv", index=False)
print("Saved:", OUTPUT_DIR / "dataset_with_volatility.csv")

Prepared data shape: (18381, 12)
Stocks: 5

,Date,Close,High,Low,Open,Volume,Return,MA_5,MA_10,MA_20,Volatility,Stock
0,2010-02-01,8649.149414,8712.148681,8495.151205,8597.350212,0,-0.000266,8550.110352,8779.747852,8929.211182,7.068376e-08,BANKNIFTY
1,2010-02-02,8468.051758,8718.548840,8453.801924,8666.599250,0,-0.021161,8504.421094,8717.238574,8897.001562,4.477675e-04,BANKNIFTY
2,2010-02-03,8631.749023,8662.849247,8489.700874,8489.700874,0,0.019147,8564.830273,8666.834082,8868.986816,3.665956e-04,BANKNIFTY
3,2010-02-04,8471.000977,8623.149596,8455.401549,8591.699767,0,-0.018798,8574.280078,8601.309863,8831.392236,3.533825e-04,BANKNIFTY
4,2010-02-05,8223.154297,8319.053571,8150.355339,8319.053571,0,-0.029695,8488.621094,8531.705664,8782.907764,8.817818e-04,BANKNIFTY

Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/dataset_with_volatility.csv

## Run BrainAutoML + Volatility Models
The next cells execute full modeling and artifact generation into `examples/volatility_output`.

In [3]:
from brain_automl.model_zoo.time_series_ai import BrainAutoMLForecast

HORIZONS = [7, 15, 30]
MAX_H = max(HORIZONS)

# Configure a broad but practical run
model = BrainAutoMLForecast(
    horizon=MAX_H,
    timestamp_column="Date",
    target_column="Volatility",
    item_id_column="Stock",
    include_backends=True,
    include_comprehensive=True,
    include_advanced_dl=False,
    output_dir=str(OUTPUT_DIR),
)

# One train pass per stock using max horizon holdout; evaluate all horizons
model.fit_all_stocks(df, horizons=HORIZONS)

multi_lb = model.multi_stock_leaderboard()
multi_lb.to_csv(OUTPUT_DIR / "brain_automl_volatility_leaderboard.csv", index=False)
print("Saved:", OUTPUT_DIR / "brain_automl_volatility_leaderboard.csv")
print("Leaderboard rows:", len(multi_lb))
display(multi_lb.head(20))

[22:37:44] INFO     Brain-AI run started
[22:37:44] INFO     Log file : /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/logs/brain_automl_20260406_223744_932751.log
[22:37:44] INFO     Output dir: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output
[22:37:44] INFO     ============================================================
[22:37:44] INFO     fit_all_stocks() starting
[22:37:44] INFO       Data shape  : (18381, 12)
[22:37:44] INFO       Horizons    : [7, 15, 30]  (max=30)
[22:37:44] INFO       Target      : Volatility
[22:37:44] INFO       Item-ID col : 'Stock'
[22:37:44] INFO     ============================================================
[22:37:44] INFO     Stocks to process: ['BANKNIFTY', 'HDFCBANK', 'NIFTY50', 'RELIANCE', 'TCS'] (5 total)
[22:37:44] INFO
──────────────────────────────────────────────────
[22:37:44] INFO     [1/5] Stock: BANKNIFTY
[22:37:45] INFO     Item: BANKNIFTY | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[22:37:45] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[22:38:23] INFO     [ OK ] autogluon_timeseries — 38.4s | RMSE=0.0001  MAE=0.0001
[22:38:23] INFO     [START] statsforecast
[22:38:46] INFO     [ OK ] statsforecast — 22.9s | RMSE=0.0001  MAE=0.0001
[22:38:46] INFO     [START] flaml
[22:39:33] INFO     [ OK ] flaml — 47.2s | RMSE=0.0001  MAE=0.0001
[22:39:33] INFO     Best backend: autogluon_timeseries | RMSE=0.0001  MAE=0.0001
[22:39:33] INFO     forecast_last_horizon complete
[22:39:33] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/predictions/BANKNIFTY_predictions_h30.csv
[22:39:33] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[22:39:33] [comprehensive] ── Stock: BANKNIFTY  (train=3647, test=30 rows)
[22:39:33] [comprehensive] combo 1/15 | BANKNIFTY/Volatility | decomp=original model=ARIMA
[22:39:34] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=222806.3203
[22:39:34] [comprehensive] combo 2/15 | BANKNIFTY/Volatility | decomp=original model=ExpSmoothing
[22:39:34] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=208960.6370
[22:39:34] [comprehensive] combo 3/15 | BANKNIFTY/Volatility | decomp=original model=LSTM
[22:41:07] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=402448.5828
[22:41:07] [comprehensive] combo 4/15 | BANKNIFTY/Volatility | decomp=original model=XGBoost
[22:41:08] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=162053.1204
[22:41:08] [comprehensive] combo 5/15 | BANKNIFTY/Volatility | decomp=original model=RandomForest
[22:41:09] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=197976.8702
[22:41:09] [comprehensive] combo 6/15 | BANKNIFTY/Volatility | decomp=decomposition+model model=ARIMA
[22:41:10] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=11074.1248
[22:41:10] [comprehensive] combo 7/15 | BANKNIFTY/Volatility | decomp=decomposition+model model=ExpSmoothing
[22:41:10] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=10232.8355
[22:41:10] [comprehensive] combo 8/15 | BANKNIFTY/Volatility | decomp=decomposition+model model=LSTM
[22:43:50] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=94576.0725
[22:43:50] [comprehensive] combo 9/15 | BANKNIFTY/Volatility | decomp=decomposition+model model=XGBoost
[22:43:51] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=97758.7172
[22:43:51] [comprehensive] combo 10/15 | BANKNIFTY/Volatility | decomp=decomposition+model model=RandomForest
[22:43:52] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=88274.1704
[22:43:52] [comprehensive] combo 11/15 | BANKNIFTY/Volatility | decomp=hybrid model=ARIMA
WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x319f3e3b0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[22:44:49] [comprehensive]    ↳ No prediction produced — skipping
[22:44:49] [comprehensive] combo 12/15 | BANKNIFTY/Volatility | decomp=hybrid model=ExpSmoothing
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x31ac8b1c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
[22:45:46] [comprehensive]    ↳ No prediction produced — skipping
[22:45:46] [comprehensive] combo 13/15 | BANKNIFTY/Volatility | decomp=hybrid model=LSTM
[22:46:43] [comprehensive]    ↳ No prediction produced — skipping
[22:46:43] [comprehensive] combo 14/15 | BANKNIFTY/Volatility | decomp=hybrid model=XGBoost
[22:47:39] [comprehensive]    ↳ No prediction produced — skipping
[22:47:39] [comprehensive] combo 15/15 | BANKNIFTY/Volatility | decomp=hybrid model=RandomForest
[22:48:36] [comprehensive]    ↳ No prediction produced — skipping
[22:48:36] [comprehensive] Done. Total results: 10
[22:48:36] INFO
──────────────────────────────────────────────────
[22:48:36] INFO     [2/5] Stock: HDFCBANK
[22:48:36] INFO     Item: HDFCBANK | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[22:48:36] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[22:49:04] INFO     [ OK ] autogluon_timeseries — 27.8s | RMSE=0.0001  MAE=0.0001
[22:49:04] INFO     [START] statsforecast
[22:49:22] INFO     [ OK ] statsforecast — 18.7s | RMSE=0.0001  MAE=0.0001
[22:49:22] INFO     [START] flaml
[22:50:18] INFO     [ OK ] flaml — 56.0s | RMSE=0.0002  MAE=0.0002
[22:50:18] INFO     Best backend: statsforecast | RMSE=0.0001  MAE=0.0001
[22:50:18] INFO     forecast_last_horizon complete
[22:50:18] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/predictions/HDFCBANK_predictions_h30.csv
[22:50:18] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[22:50:18] [comprehensive] ── Stock: HDFCBANK  (train=3651, test=30 rows)
[22:50:18] [comprehensive] combo 1/15 | HDFCBANK/Volatility | decomp=original model=ARIMA
[22:50:19] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=1019823.4979
[22:50:19] [comprehensive] combo 2/15 | HDFCBANK/Volatility | decomp=original model=ExpSmoothing
[22:50:19] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=881313.8055
[22:50:19] [comprehensive] combo 3/15 | HDFCBANK/Volatility | decomp=original model=LSTM
[22:52:22] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=853530.5960
[22:52:22] [comprehensive] combo 4/15 | HDFCBANK/Volatility | decomp=original model=XGBoost
[22:52:22] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=714579.4074
[22:52:22] [comprehensive] combo 5/15 | HDFCBANK/Volatility | decomp=original model=RandomForest
[22:52:23] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=621183.6378
[22:52:23] [comprehensive] combo 6/15 | HDFCBANK/Volatility | decomp=decomposition+model model=ARIMA
[22:52:24] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=300202.5910
[22:52:24] [comprehensive] combo 7/15 | HDFCBANK/Volatility | decomp=decomposition+model model=ExpSmoothing
[22:52:24] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=93485.6536
[22:52:24] [comprehensive] combo 8/15 | HDFCBANK/Volatility | decomp=decomposition+model model=LSTM
[22:55:02] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=355795.6682
[22:55:02] [comprehensive] combo 9/15 | HDFCBANK/Volatility | decomp=decomposition+model model=XGBoost
[22:55:03] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=317043.6695
[22:55:03] [comprehensive] combo 10/15 | HDFCBANK/Volatility | decomp=decomposition+model model=RandomForest
[22:55:05] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=340713.8000
[22:55:05] [comprehensive] combo 11/15 | HDFCBANK/Volatility | decomp=hybrid model=ARIMA
[22:56:11] [comprehensive]    ↳ No prediction produced — skipping
[22:56:11] [comprehensive] combo 12/15 | HDFCBANK/Volatility | decomp=hybrid model=ExpSmoothing
[22:57:19] [comprehensive]    ↳ No prediction produced — skipping
[22:57:19] [comprehensive] combo 13/15 | HDFCBANK/Volatility | decomp=hybrid model=LSTM
[23:15:16] [comprehensive]    ↳ No prediction produced — skipping
[23:15:16] [comprehensive] combo 14/15 | HDFCBANK/Volatility | decomp=hybrid model=XGBoost
[23:21:34] [comprehensive]    ↳ No prediction produced — skipping
[23:21:34] [comprehensive] combo 15/15 | HDFCBANK/Volatility | decomp=hybrid model=RandomForest
[23:22:42] [comprehensive]    ↳ No prediction produced — skipping
[23:22:42] [comprehensive] Done. Total results: 10
[23:22:42] INFO
──────────────────────────────────────────────────
[23:22:42] INFO     [3/5] Stock: NIFTY50
[23:22:42] INFO     Item: NIFTY50 | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[23:22:42] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[23:23:09] INFO     [ OK ] autogluon_timeseries — 27.3s | RMSE=0.0001  MAE=0.0001
[23:23:09] INFO     [START] statsforecast
[23:23:25] INFO     [ OK ] statsforecast — 15.6s | RMSE=0.0001  MAE=0.0001
[23:23:25] INFO     [START] flaml
[23:24:11] INFO     [ OK ] flaml — 46.4s | RMSE=0.0001  MAE=0.0001
[23:24:11] INFO     Best backend: flaml | RMSE=0.0001  MAE=0.0001
[23:24:11] INFO     forecast_last_horizon complete
[23:24:11] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/predictions/NIFTY50_predictions_h30.csv
[23:24:11] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[23:24:11] [comprehensive] ── Stock: NIFTY50  (train=3631, test=30 rows)
[23:24:11] [comprehensive] combo 1/15 | NIFTY50/Volatility | decomp=original model=ARIMA
[23:24:12] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=14105331.6960
[23:24:12] [comprehensive] combo 2/15 | NIFTY50/Volatility | decomp=original model=ExpSmoothing
[23:24:12] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=13117948.1989
[23:24:12] [comprehensive] combo 3/15 | NIFTY50/Volatility | decomp=original model=LSTM
[23:25:57] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=10450318.6086
[23:25:57] [comprehensive] combo 4/15 | NIFTY50/Volatility | decomp=original model=XGBoost
[23:25:57] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=10483110.0609
[23:25:57] [comprehensive] combo 5/15 | NIFTY50/Volatility | decomp=original model=RandomForest
[23:25:58] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=13624465.5927
[23:25:58] [comprehensive] combo 6/15 | NIFTY50/Volatility | decomp=decomposition+model model=ARIMA
[23:25:59] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=3743281.1064
[23:25:59] [comprehensive] combo 7/15 | NIFTY50/Volatility | decomp=decomposition+model model=ExpSmoothing
[23:25:59] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=1086883.9579
[23:25:59] [comprehensive] combo 8/15 | NIFTY50/Volatility | decomp=decomposition+model model=LSTM
[23:29:01] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=7563449.7406
[23:29:01] [comprehensive] combo 9/15 | NIFTY50/Volatility | decomp=decomposition+model model=XGBoost
[23:29:01] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=5538754.1366
[23:29:01] [comprehensive] combo 10/15 | NIFTY50/Volatility | decomp=decomposition+model model=RandomForest
[23:29:03] [comprehensive]    ✓ RMSE=0.0001  MAE=0.0001  MAPE=5557045.1673
[23:29:03] [comprehensive] combo 11/15 | NIFTY50/Volatility | decomp=hybrid model=ARIMA
[23:30:10] [comprehensive]    ↳ No prediction produced — skipping
[23:30:10] [comprehensive] combo 12/15 | NIFTY50/Volatility | decomp=hybrid model=ExpSmoothing
[23:31:18] [comprehensive]    ↳ No prediction produced — skipping
[23:31:18] [comprehensive] combo 13/15 | NIFTY50/Volatility | decomp=hybrid model=LSTM
[23:32:25] [comprehensive]    ↳ No prediction produced — skipping
[23:32:25] [comprehensive] combo 14/15 | NIFTY50/Volatility | decomp=hybrid model=XGBoost
[23:33:32] [comprehensive]    ↳ No prediction produced — skipping
[23:33:32] [comprehensive] combo 15/15 | NIFTY50/Volatility | decomp=hybrid model=RandomForest
[23:34:40] [comprehensive]    ↳ No prediction produced — skipping
[23:34:40] [comprehensive] Done. Total results: 10
[23:34:40] INFO
──────────────────────────────────────────────────
[23:34:40] INFO     [4/5] Stock: RELIANCE
[23:34:40] INFO     Item: RELIANCE | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[23:34:40] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[23:35:06] INFO     [ OK ] autogluon_timeseries — 26.8s | RMSE=0.0002  MAE=0.0002
[23:35:06] INFO     [START] statsforecast
[23:35:35] INFO     [ OK ] statsforecast — 29.0s | RMSE=0.0002  MAE=0.0001
[23:35:35] INFO     [START] flaml
[23:36:07] INFO     [ OK ] flaml — 32.0s | RMSE=0.0002  MAE=0.0002
[23:36:07] INFO     Best backend: statsforecast | RMSE=0.0002  MAE=0.0001
[23:36:07] INFO     forecast_last_horizon complete
[23:36:07] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/predictions/RELIANCE_predictions_h30.csv
[23:36:07] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[23:36:07] [comprehensive] ── Stock: RELIANCE  (train=3651, test=30 rows)
[23:36:07] [comprehensive] combo 1/15 | RELIANCE/Volatility | decomp=original model=ARIMA
[23:36:08] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=4451.5912
[23:36:08] [comprehensive] combo 2/15 | RELIANCE/Volatility | decomp=original model=ExpSmoothing
[23:36:08] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=4413.0119
[23:36:08] [comprehensive] combo 3/15 | RELIANCE/Volatility | decomp=original model=LSTM
[23:37:51] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=7086.4954
[23:37:51] [comprehensive] combo 4/15 | RELIANCE/Volatility | decomp=original model=XGBoost
[23:37:52] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0002  MAPE=5114.8034
[23:37:52] [comprehensive] combo 5/15 | RELIANCE/Volatility | decomp=original model=RandomForest
[23:37:53] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=5329.2959
[23:37:53] [comprehensive] combo 6/15 | RELIANCE/Volatility | decomp=decomposition+model model=ARIMA
[23:37:53] [comprehensive]    ✓ RMSE=0.0003  MAE=0.0001  MAPE=792.5951
[23:37:53] [comprehensive] combo 7/15 | RELIANCE/Volatility | decomp=decomposition+model model=ExpSmoothing
[23:37:53] [comprehensive]    ✓ RMSE=0.0003  MAE=0.0001  MAPE=403.7888
[23:37:53] [comprehensive] combo 8/15 | RELIANCE/Volatility | decomp=decomposition+model model=LSTM
[23:41:05] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=3934.7500
[23:41:05] [comprehensive] combo 9/15 | RELIANCE/Volatility | decomp=decomposition+model model=XGBoost
[23:41:06] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=2238.8468
[23:41:06] [comprehensive] combo 10/15 | RELIANCE/Volatility | decomp=decomposition+model model=RandomForest
[23:41:08] [comprehensive]    ✓ RMSE=0.0002  MAE=0.0001  MAPE=2199.7434
[23:41:08] [comprehensive] combo 11/15 | RELIANCE/Volatility | decomp=hybrid model=ARIMA
[23:42:16] [comprehensive]    ↳ No prediction produced — skipping
[23:42:16] [comprehensive] combo 12/15 | RELIANCE/Volatility | decomp=hybrid model=ExpSmoothing
[23:43:24] [comprehensive]    ↳ No prediction produced — skipping
[23:43:24] [comprehensive] combo 13/15 | RELIANCE/Volatility | decomp=hybrid model=LSTM
[23:44:32] [comprehensive]    ↳ No prediction produced — skipping
[23:44:32] [comprehensive] combo 14/15 | RELIANCE/Volatility | decomp=hybrid model=XGBoost
[23:45:40] [comprehensive]    ↳ No prediction produced — skipping
[23:45:40] [comprehensive] combo 15/15 | RELIANCE/Volatility | decomp=hybrid model=RandomForest
[23:46:48] [comprehensive]    ↳ No prediction produced — skipping
[23:46:48] [comprehensive] Done. Total results: 10
[23:46:48] INFO
──────────────────────────────────────────────────
[23:46:48] INFO     [5/5] Stock: TCS
[23:46:48] INFO     Item: TCS | Freq: B | Horizon: 30 | Train rows: 3862 | Backends: ['autogluon_timeseries', 'statsforecast', 'flaml']

Backends:   0%|          | 0/3 [00:00<?, ?backend/s]

[23:46:48] INFO     [START] autogluon_timeseries

Warning: path already exists! This predictor may overwrite an existing predictor! path="/Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/brain_automl_output/autogluon_timeseries"

[23:47:12] INFO     [ OK ] autogluon_timeseries — 23.2s | RMSE=0.0004  MAE=0.0002
[23:47:12] INFO     [START] statsforecast
[23:47:18] INFO     [ OK ] statsforecast — 6.8s | RMSE=0.0003  MAE=0.0002
[23:47:18] INFO     [START] flaml
[23:48:02] INFO     [ OK ] flaml — 43.6s | RMSE=0.0003  MAE=0.0002
[23:48:02] INFO     Best backend: statsforecast | RMSE=0.0003  MAE=0.0002
[23:48:02] INFO     forecast_last_horizon complete
[23:48:02] INFO     Saved per-stock predictions to: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/predictions/TCS_predictions_h30.csv
[23:48:02] [comprehensive] Starting: 1 stock(s), 1 column(s), 3 decompositions, 5 models  →  up to 15 combinations
[23:48:02] [comprehensive] ── Stock: TCS  (train=3651, test=30 rows)
[23:48:02] [comprehensive] combo 1/15 | TCS/Volatility | decomp=original model=ARIMA
[23:48:02] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1948.5729
[23:48:02] [comprehensive] combo 2/15 | TCS/Volatility | decomp=original model=ExpSmoothing
[23:48:02] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1960.4031
[23:48:02] [comprehensive] combo 3/15 | TCS/Volatility | decomp=original model=LSTM
[23:49:44] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1689.1584
[23:49:44] [comprehensive] combo 4/15 | TCS/Volatility | decomp=original model=XGBoost
[23:49:45] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1553.1870
[23:49:45] [comprehensive] combo 5/15 | TCS/Volatility | decomp=original model=RandomForest
[23:49:46] [comprehensive]    ✓ RMSE=0.0003  MAE=0.0002  MAPE=2276.7450
[23:49:46] [comprehensive] combo 6/15 | TCS/Volatility | decomp=decomposition+model model=ARIMA
[23:49:46] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=214.4875
[23:49:46] [comprehensive] combo 7/15 | TCS/Volatility | decomp=decomposition+model model=ExpSmoothing
[23:49:46] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=188.4502
[23:49:46] [comprehensive] combo 8/15 | TCS/Volatility | decomp=decomposition+model model=LSTM
[23:52:25] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1262.7780
[23:52:25] [comprehensive] combo 9/15 | TCS/Volatility | decomp=decomposition+model model=XGBoost
[23:52:25] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1370.7477
[23:52:25] [comprehensive] combo 10/15 | TCS/Volatility | decomp=decomposition+model model=RandomForest
[23:52:27] [comprehensive]    ✓ RMSE=0.0004  MAE=0.0002  MAPE=1084.1325
[23:52:27] [comprehensive] combo 11/15 | TCS/Volatility | decomp=hybrid model=ARIMA
[23:53:31] [comprehensive]    ↳ No prediction produced — skipping
[23:53:31] [comprehensive] combo 12/15 | TCS/Volatility | decomp=hybrid model=ExpSmoothing
[23:54:35] [comprehensive]    ↳ No prediction produced — skipping
[23:54:35] [comprehensive] combo 13/15 | TCS/Volatility | decomp=hybrid model=LSTM
[23:55:38] [comprehensive]    ↳ No prediction produced — skipping
[23:55:38] [comprehensive] combo 14/15 | TCS/Volatility | decomp=hybrid model=XGBoost
[23:56:42] [comprehensive]    ↳ No prediction produced — skipping
[23:56:42] [comprehensive] combo 15/15 | TCS/Volatility | decomp=hybrid model=RandomForest
[23:57:45] [comprehensive]    ↳ No prediction produced — skipping
[23:57:45] [comprehensive] Done. Total results: 10
[23:57:45] INFO
fit_all_stocks() complete — 285 leaderboard rows across 5 stocks
Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/brain_automl_volatility_leaderboard.csv
Leaderboard rows: 285

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column
0,BANKNIFTY,7,decomposition+model/XGBoost,classical,0.000069,NaN,0.000097,9.775872e+04,NaN,NaN,NaN,NaN,Volatility
1,BANKNIFTY,7,decomposition+model/LSTM,classical,0.000071,NaN,0.000100,9.457607e+04,NaN,NaN,NaN,NaN,Volatility
2,BANKNIFTY,7,decomposition+model/RandomForest,classical,0.000070,NaN,0.000103,8.827417e+04,NaN,NaN,NaN,NaN,Volatility
3,BANKNIFTY,7,original/XGBoost,classical,0.000087,NaN,0.000105,1.620531e+05,NaN,NaN,NaN,NaN,Volatility
4,NIFTY50,7,original/XGBoost,classical,0.000070,NaN,0.000111,1.048311e+07,NaN,NaN,NaN,NaN,Volatility
5,NIFTY50,7,original/RandomForest,classical,0.000076,NaN,0.000112,1.362447e+07,NaN,NaN,NaN,NaN,Volatility
6,NIFTY50,7,original/ExpSmoothing,classical,0.000074,NaN,0.000112,1.311795e+07,NaN,NaN,NaN,NaN,Volatility
7,NIFTY50,7,original/ARIMA,classical,0.000076,NaN,0.000113,1.410533e+07,NaN,NaN,NaN,NaN,Volatility
8,NIFTY50,7,original/LSTM,classical,0.000068,NaN,0.000113,1.045032e+07,NaN,NaN,NaN,NaN,Volatility
9,BANKNIFTY,7,original/ExpSmoothing,classical,0.000101,NaN,0.000115,2.089606e+05,NaN,NaN,NaN,NaN,Volatility
10,NIFTY50,7,decomposition+model/XGBoost,classical,0.000062,NaN,0.000115,5.538754e+06,NaN,NaN,NaN,NaN,Volatility
11,BANKNIFTY,7,arima,flaml,0.000088,1.323460e-08,0.000115,2.068530e+04,102.789333,80.051318,0.29701,0.407382,NaN
12,NIFTY50,7,decomposition+model/LSTM,classical,0.000065,NaN,0.000116,7.563450e+06,NaN,NaN,NaN,NaN,Volatility
13,NIFTY50,7,decomposition+model/RandomForest,classical,0.000063,NaN,0.000117,5.557045e+06,NaN,NaN,NaN,NaN,Volatility
14,BANKNIFTY,7,original/RandomForest,classical,0.000102,NaN,0.000117,1.979769e+05,NaN,NaN,NaN,NaN,Volatility
15,BANKNIFTY,7,decomposition+model/ARIMA,classical,0.000066,NaN,0.000117,1.107412e+04,NaN,NaN,NaN,NaN,Volatility
16,BANKNIFTY,7,original/ARIMA,classical,0.000107,NaN,0.000120,2.228063e+05,NaN,NaN,NaN,NaN,Volatility
17,BANKNIFTY,7,decomposition+model/ExpSmoothing,classical,0.000073,NaN,0.000123,1.023284e+04,NaN,NaN,NaN,NaN,Volatility
18,NIFTY50,7,decomposition+model/ARIMA,classical,0.000064,NaN,0.000123,3.743281e+06,NaN,NaN,NaN,NaN,Volatility
19,NIFTY50,7,decomposition+model/ExpSmoothing,classical,0.000065,NaN,0.000126,1.086884e+06,NaN,NaN,NaN,NaN,Volatility

In [4]:
# Best model summaries
best_per_stock = model.best_model_per_stock()
overall_best = model.overall_best_models()

best_per_stock.to_csv(OUTPUT_DIR / "best_model_per_stock_rmse.csv", index=False)
overall_best.to_csv(OUTPUT_DIR / "overall_best_models_rmse.csv", index=False)

print("Saved:", OUTPUT_DIR / "best_model_per_stock_rmse.csv")
print("Saved:", OUTPUT_DIR / "overall_best_models_rmse.csv")
display(best_per_stock.head(20))
display(overall_best.head(20))

Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/best_model_per_stock_rmse.csv
Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/overall_best_models_rmse.csv

,stock,horizon,model,library,mae,mse,rmse,mape,smape,wape,mase,r2,column
0,BANKNIFTY,7,decomposition+model/XGBoost,classical,0.000069,1.323460e-08,0.000097,9.775872e+04,102.789333,80.051318,0.297010,0.407382,Volatility
1,BANKNIFTY,15,decomposition+model/XGBoost,classical,0.000069,9.554397e-09,0.000097,9.775872e+04,113.636682,108.466433,0.262799,0.263593,Volatility
2,BANKNIFTY,30,decomposition+model/XGBoost,classical,0.000069,9.964374e-09,0.000097,9.775872e+04,118.614252,100.945358,0.236006,-0.011117,Volatility
3,HDFCBANK,7,WeightedEnsemble,autogluon_timeseries,0.000097,1.863601e-08,0.000137,2.629944e+06,97.519582,62.270316,0.331825,0.380446,Volatility
4,HDFCBANK,15,decomposition+model/XGBoost,classical,0.000103,2.072093e-08,0.000141,3.170437e+05,116.337430,104.136686,0.401921,0.050984,Volatility
5,HDFCBANK,30,AutoARIMA,statsforecast,0.000112,1.879401e-08,0.000137,9.314938e+05,119.055112,115.636517,0.384697,-0.190378,Volatility
6,NIFTY50,7,original/XGBoost,classical,0.000070,3.340457e-08,0.000111,1.048311e+07,103.372609,80.035763,0.789550,0.012115,Volatility
7,NIFTY50,15,original/XGBoost,classical,0.000070,1.662980e-08,0.000111,1.048311e+07,119.809807,84.405292,0.491257,0.159010,Volatility
8,NIFTY50,30,arima,flaml,0.000065,1.157540e-08,0.000108,2.223929e+06,135.519937,93.469617,0.432021,0.083796,Volatility
9,RELIANCE,7,original/XGBoost,classical,0.000155,1.074908e-07,0.000218,5.114803e+03,75.033337,65.794041,0.517481,0.164967,Volatility
10,RELIANCE,15,original/XGBoost,classical,0.000155,6.527246e-08,0.000218,5.114803e+03,61.937477,63.231616,0.341640,0.084963,Volatility
11,RELIANCE,30,original/XGBoost,classical,0.000155,5.174268e-08,0.000218,5.114803e+03,88.879555,73.479891,0.301134,-0.079004,Volatility
12,TCS,7,original/RandomForest,classical,0.000226,3.224792e-07,0.000349,2.276745e+03,109.123243,91.937435,0.996063,-0.025194,Volatility
13,TCS,15,original/RandomForest,classical,0.000226,1.817676e-07,0.000349,2.276745e+03,126.511143,117.441027,0.793394,0.015661,Volatility
14,TCS,30,AutoARIMA,statsforecast,0.000217,1.110923e-07,0.000333,2.495390e+03,129.076202,122.345131,0.631135,-0.005668,Volatility

,model,library,horizon,mean_rmse,std_rmse,n_stocks
0,original/XGBoost,classical,7,0.000189,0.000102,5
1,decomposition+model/LSTM,classical,7,0.000191,0.000113,5
2,original/RandomForest,classical,7,0.000191,0.000098,5
3,decomposition+model/XGBoost,classical,7,0.000194,0.000119,5
4,decomposition+model/RandomForest,classical,7,0.000195,0.000116,5
5,original/XGBoost,classical,15,0.000189,0.000102,5
6,decomposition+model/LSTM,classical,15,0.000191,0.000113,5
7,original/RandomForest,classical,15,0.000191,0.000098,5
8,decomposition+model/XGBoost,classical,15,0.000194,0.000119,5
9,decomposition+model/RandomForest,classical,15,0.000195,0.000116,5
10,arima,flaml,30,0.000180,0.000109,4
11,AutoARIMA,statsforecast,30,0.000186,0.000095,5
12,original/XGBoost,classical,30,0.000189,0.000102,5
13,WeightedEnsemble,autogluon_timeseries,30,0.000190,0.000103,5
14,ETS,autogluon_internal,30,0.000190,0.000095,5

In [5]:
# Run volatility baselines per stock (EWMA, GARCH-family via arch)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

try:
    from arch import arch_model
    arch_available = True
except Exception as e:
    arch_available = False
    print("arch unavailable:", e)

garch_dir = OUTPUT_DIR / "garch_egarch"
garch_dir.mkdir(parents=True, exist_ok=True)

def metric_row(stock, model_name, horizon, y_true, y_pred):
    return {
        "stock": stock,
        "model_col": model_name,
        "horizon": int(horizon),
        "mae": float(mean_absolute_error(y_true, y_pred)),
        "mse": float(mean_squared_error(y_true, y_pred)),
        "rmse": float(np.sqrt(mean_squared_error(y_true, y_pred))),
        "mape": float(np.mean(np.abs((y_true - y_pred) / np.maximum(np.abs(y_true), 1e-8))) * 100.0),
        "r2": float(r2_score(y_true, y_pred)),
    }

garch_rows = []
for stock in sorted(df["Stock"].unique()):
    sdf = df[df["Stock"] == stock].sort_values("Date").copy()
    sdf["ret"] = np.log(sdf["Close"]).diff().fillna(0.0) * 100.0

    # Align evaluation to last max horizon points
    eval_idx = sdf.index[-MAX_H:] if len(sdf) >= MAX_H else sdf.index
    actual_vol_all = sdf.loc[eval_idx, "Volatility"].to_numpy(dtype=float)
    if len(actual_vol_all) < 2:
        print(f"Skipping {stock}: not enough observations for baseline evaluation")
        continue

    # EWMA (RiskMetrics-style) baseline with lambda=0.94 for daily data
    lam = 0.94
    ret = sdf["ret"].to_numpy(dtype=float) / 100.0
    ewma_var = np.zeros_like(ret, dtype=float)
    ewma_var[0] = np.var(ret) if len(ret) > 1 else 0.0
    for i in range(1, len(ret)):
        ewma_var[i] = lam * ewma_var[i - 1] + (1.0 - lam) * (ret[i - 1] ** 2)
    ewma_vol = np.sqrt(np.maximum(ewma_var, 0.0))
    ewma_pred_all = ewma_vol[-len(eval_idx):]

    # Evaluate EWMA for each horizon separately
    for h in HORIZONS:
        if len(actual_vol_all) >= h:
            actual_vol_h = actual_vol_all[-h:]
            ewma_pred_h = ewma_pred_all[-h:]
            garch_rows.append(metric_row(stock, "ewma_0p94", h, actual_vol_h, ewma_pred_h))

    # Save full predictions for the largest horizon
    pred_df_ewma = pd.DataFrame({
        "Date": sdf.loc[eval_idx, "Date"].values,
        "actual_volatility": actual_vol_all,
        "predicted_volatility": ewma_pred_all
    })
    pred_df_ewma.to_csv(garch_dir / f"{stock}_ewma_0p94_predictions.csv", index=False)
    print(f"Saved EWMA predictions for {stock}")

    if arch_available:
        arch_specs = [
            {"name": "garch", "vol": "Garch", "kwargs": {"p": 1, "q": 1}},
            {"name": "egarch", "vol": "EGARCH", "kwargs": {"p": 1, "q": 1}},
            {"name": "gjr_garch", "vol": "GARCH", "kwargs": {"p": 1, "o": 1, "q": 1}},
        ]
        for spec in arch_specs:
            try:
                am = arch_model(
                    sdf["ret"],
                    mean="Zero",
                    vol=spec["vol"],
                    dist="normal",
                    **spec["kwargs"],
                )
                res = am.fit(disp="off")
                cond_vol = (res.conditional_volatility / 100.0).reindex(sdf.index).to_numpy(dtype=float)
                pred_vol_all = cond_vol[-len(eval_idx):]

                # Evaluate each GARCH variant for each horizon separately
                for h in HORIZONS:
                    if len(actual_vol_all) >= h:
                        actual_vol_h = actual_vol_all[-h:]
                        pred_vol_h = pred_vol_all[-h:]
                        garch_rows.append(metric_row(stock, spec["name"], h, actual_vol_h, pred_vol_h))

                # Save full predictions for the largest horizon
                pred_df = pd.DataFrame({
                    "Date": sdf.loc[eval_idx, "Date"].values,
                    "actual_volatility": actual_vol_all,
                    "predicted_volatility": pred_vol_all
                })
                pred_df.to_csv(garch_dir / f"{stock}_{spec['name']}_predictions.csv", index=False)
                print(f"Saved {spec['name']} predictions for {stock}")
            except Exception as e:
                print(f"{spec['name']} failed for {stock}: {e}")
    else:
        print("Skipping arch-based models because arch is not installed.")

garch_metrics = pd.DataFrame(garch_rows)
if not garch_metrics.empty:
    garch_metrics.to_csv(OUTPUT_DIR / "garch_egarch_metrics.csv", index=False)
    print("Saved:", OUTPUT_DIR / "garch_egarch_metrics.csv")
display(garch_metrics.head(20))

Saved EWMA predictions for BANKNIFTY
Saved garch predictions for BANKNIFTY
Saved egarch predictions for BANKNIFTY
Saved gjr_garch predictions for BANKNIFTY
Saved EWMA predictions for HDFCBANK
Saved garch predictions for HDFCBANK
Saved egarch predictions for HDFCBANK
Saved gjr_garch predictions for HDFCBANK
Saved EWMA predictions for NIFTY50
Saved garch predictions for NIFTY50
Saved egarch predictions for NIFTY50
Saved gjr_garch predictions for NIFTY50
Saved EWMA predictions for RELIANCE
Saved garch predictions for RELIANCE
Saved egarch predictions for RELIANCE
Saved gjr_garch predictions for RELIANCE
Saved EWMA predictions for TCS
Saved garch predictions for TCS
Saved egarch predictions for TCS
Saved gjr_garch predictions for TCS
Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/garch_egarch_metrics.csv

,stock,model_col,horizon,mae,mse,rmse,mape,r2
0,BANKNIFTY,ewma_0p94,7,0.009245,0.000086,0.009252,2.028301e+05,-11054.368630
1,BANKNIFTY,ewma_0p94,15,0.008964,0.000081,0.008975,5.784715e+06,-12097.378925
2,BANKNIFTY,ewma_0p94,30,0.009651,0.000094,0.009687,3.368612e+06,-9568.304976
3,BANKNIFTY,garch,7,0.010238,0.000105,0.010247,2.246907e+05,-13560.238507
4,BANKNIFTY,garch,15,0.009760,0.000096,0.009779,6.177651e+06,-14363.231388
5,BANKNIFTY,garch,30,0.010460,0.000110,0.010501,3.610010e+06,-11245.826056
6,BANKNIFTY,egarch,7,0.010547,0.000112,0.010563,2.328942e+05,-14411.200488
7,BANKNIFTY,egarch,15,0.009914,0.000099,0.009946,6.245370e+06,-14857.003280
8,BANKNIFTY,egarch,30,0.010744,0.000117,0.010804,3.672298e+06,-11904.182156
9,BANKNIFTY,gjr_garch,7,0.011062,0.000123,0.011074,2.418259e+05,-15838.357851
10,BANKNIFTY,gjr_garch,15,0.010066,0.000102,0.010124,5.977662e+06,-15393.064102
11,BANKNIFTY,gjr_garch,30,0.010587,0.000113,0.010647,3.489757e+06,-11559.500874
12,HDFCBANK,ewma_0p94,7,0.010947,0.000120,0.010952,1.035738e+05,-13182.113840
13,HDFCBANK,ewma_0p94,15,0.011075,0.000123,0.011085,1.643059e+05,-13143.423050
14,HDFCBANK,ewma_0p94,30,0.012097,0.000148,0.012150,4.889778e+06,-7605.380734
15,HDFCBANK,garch,7,0.011693,0.000137,0.011696,1.104257e+05,-15035.192880
16,HDFCBANK,garch,15,0.011678,0.000137,0.011685,1.710678e+05,-14604.695929
17,HDFCBANK,garch,30,0.012563,0.000159,0.012604,5.012192e+06,-8183.566438
18,HDFCBANK,egarch,7,0.012113,0.000147,0.012120,1.158080e+05,-16145.680298
19,HDFCBANK,egarch,15,0.011848,0.000141,0.011864,1.755435e+05,-15056.234960

In [6]:
# Merge BrainAutoML and volatility-baseline metrics into one comparison table
brain_metrics = multi_lb.copy()
brain_metrics = brain_metrics.rename(columns={"model": "model_col"})
brain_metrics["source"] = "brain_automl"

if not garch_metrics.empty:
    garch_cmp = garch_metrics.copy()
    garch_cmp["source"] = "vol_baseline"
    common_cols = sorted(set(brain_metrics.columns).intersection(set(garch_cmp.columns)))
    combined = pd.concat([brain_metrics[common_cols], garch_cmp[common_cols]], ignore_index=True)
else:
    combined = brain_metrics.copy()

combined.to_csv(OUTPUT_DIR / "combined_volatility_metrics.csv", index=False)
print("Saved:", OUTPUT_DIR / "combined_volatility_metrics.csv")
display(combined.head(20))

pub_summary = (
    combined.groupby(["source", "model_col", "horizon"], as_index=False)
    .agg(
        mean_rmse=("rmse", "mean"),
        mean_mae=("mae", "mean"),
        mean_mape=("mape", "mean"),
        mean_r2=("r2", "mean"),
        n_stocks=("stock", "nunique")
    )
    .sort_values(["horizon", "mean_rmse"])
    .reset_index(drop=True)
)

pub_summary.to_csv(OUTPUT_DIR / "publication_summary_by_horizon.csv", index=False)
print("Saved:", OUTPUT_DIR / "publication_summary_by_horizon.csv")
display(pub_summary.head(30))

Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/combined_volatility_metrics.csv

,horizon,mae,mape,model_col,mse,r2,rmse,source,stock
0,7,0.000069,9.775872e+04,decomposition+model/XGBoost,NaN,NaN,0.000097,brain_automl,BANKNIFTY
1,7,0.000071,9.457607e+04,decomposition+model/LSTM,NaN,NaN,0.000100,brain_automl,BANKNIFTY
2,7,0.000070,8.827417e+04,decomposition+model/RandomForest,NaN,NaN,0.000103,brain_automl,BANKNIFTY
3,7,0.000087,1.620531e+05,original/XGBoost,NaN,NaN,0.000105,brain_automl,BANKNIFTY
4,7,0.000070,1.048311e+07,original/XGBoost,NaN,NaN,0.000111,brain_automl,NIFTY50
5,7,0.000076,1.362447e+07,original/RandomForest,NaN,NaN,0.000112,brain_automl,NIFTY50
6,7,0.000074,1.311795e+07,original/ExpSmoothing,NaN,NaN,0.000112,brain_automl,NIFTY50
7,7,0.000076,1.410533e+07,original/ARIMA,NaN,NaN,0.000113,brain_automl,NIFTY50
8,7,0.000068,1.045032e+07,original/LSTM,NaN,NaN,0.000113,brain_automl,NIFTY50
9,7,0.000101,2.089606e+05,original/ExpSmoothing,NaN,NaN,0.000115,brain_automl,BANKNIFTY
10,7,0.000062,5.538754e+06,decomposition+model/XGBoost,NaN,NaN,0.000115,brain_automl,NIFTY50
11,7,0.000088,2.068530e+04,arima,1.323460e-08,0.407382,0.000115,brain_automl,BANKNIFTY
12,7,0.000065,7.563450e+06,decomposition+model/LSTM,NaN,NaN,0.000116,brain_automl,NIFTY50
13,7,0.000063,5.557045e+06,decomposition+model/RandomForest,NaN,NaN,0.000117,brain_automl,NIFTY50
14,7,0.000102,1.979769e+05,original/RandomForest,NaN,NaN,0.000117,brain_automl,BANKNIFTY
15,7,0.000066,1.107412e+04,decomposition+model/ARIMA,NaN,NaN,0.000117,brain_automl,BANKNIFTY
16,7,0.000107,2.228063e+05,original/ARIMA,NaN,NaN,0.000120,brain_automl,BANKNIFTY
17,7,0.000073,1.023284e+04,decomposition+model/ExpSmoothing,NaN,NaN,0.000123,brain_automl,BANKNIFTY
18,7,0.000064,3.743281e+06,decomposition+model/ARIMA,NaN,NaN,0.000123,brain_automl,NIFTY50
19,7,0.000065,1.086884e+06,decomposition+model/ExpSmoothing,NaN,NaN,0.000126,brain_automl,NIFTY50

Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/publication_summary_by_horizon.csv

,source,model_col,horizon,mean_rmse,mean_mae,mean_mape,mean_r2,n_stocks
0,brain_automl,original/XGBoost,7,0.000189,0.000130,2.273282e+06,NaN,5
1,brain_automl,decomposition+model/LSTM,7,0.000191,0.000116,1.603804e+06,NaN,5
2,brain_automl,original/RandomForest,7,0.000191,0.000138,2.890246e+06,NaN,5
3,brain_automl,decomposition+model/XGBoost,7,0.000194,0.000115,1.191433e+06,NaN,5
4,brain_automl,decomposition+model/RandomForest,7,0.000195,0.000114,1.197863e+06,NaN,5
5,brain_automl,original/ExpSmoothing,7,0.000196,0.000138,2.842919e+06,NaN,5
6,brain_automl,original/ARIMA,7,0.000202,0.000145,3.070872e+06,NaN,5
7,brain_automl,decomposition+model/ARIMA,7,0.000210,0.000115,8.111130e+05,NaN,5
8,brain_automl,original/LSTM,7,0.000217,0.000161,2.343015e+06,NaN,5
9,brain_automl,decomposition+model/ExpSmoothing,7,0.000218,0.000119,2.382389e+05,NaN,5
10,brain_automl,arima,7,0.000267,0.000180,1.492198e+06,0.013540,4
11,brain_automl,DirectTabular,7,0.000289,0.000181,6.251835e+05,-0.000352,5
12,brain_automl,ETS,7,0.000296,0.000187,6.188953e+05,-0.046766,5
13,brain_automl,WeightedEnsemble,7,0.000305,0.000175,5.278643e+05,-0.122660,5
14,brain_automl,Theta,7,0.000319,0.000204,4.777540e+05,-0.340117,5
15,brain_automl,AutoARIMA,7,0.000320,0.000205,8.007246e+05,-0.313062,5
16,brain_automl,Naive,7,0.000357,0.000225,1.707253e+06,-0.906034,5
17,brain_automl,RecursiveTabular,7,0.000360,0.000252,1.899163e+06,-0.880298,5
18,brain_automl,SeasonalNaive,7,0.000378,0.000270,1.704231e+06,-1.210045,5
19,brain_automl,xgb_limitdepth,7,0.000388,0.000224,8.080866e+02,-0.170510,1
20,vol_baseline,ewma_0p94,7,0.010913,0.010904,2.730649e+06,-9485.702024,5
21,vol_baseline,garch,7,0.011845,0.011835,2.863474e+06,-11137.679684,5
22,vol_baseline,egarch,7,0.012181,0.012163,2.936819e+06,-11869.161041,5
23,vol_baseline,gjr_garch,7,0.012591,0.012577,3.192315e+06,-12750.436042,5
24,brain_automl,original/XGBoost,15,0.000189,0.000130,2.273282e+06,NaN,5
25,brain_automl,decomposition+model/LSTM,15,0.000191,0.000116,1.603804e+06,NaN,5
26,brain_automl,original/RandomForest,15,0.000191,0.000138,2.890246e+06,NaN,5
27,brain_automl,decomposition+model/XGBoost,15,0.000194,0.000115,1.191433e+06,NaN,5
28,brain_automl,decomposition+model/RandomForest,15,0.000195,0.000114,1.197863e+06,NaN,5
29,brain_automl,original/ExpSmoothing,15,0.000196,0.000138,2.842919e+06,NaN,5

In [7]:
# Plots and saved artifacts
import plotly.express as px

plot_dir = OUTPUT_DIR / "plots"
plot_dir.mkdir(parents=True, exist_ok=True)

if not pub_summary.empty:
    fig_rmse = px.bar(
        pub_summary,
        x="model_col",
        y="mean_rmse",
        color="source",
        facet_col="horizon",
        title="Volatility Forecast RMSE Comparison by Horizon"
    )
    fig_rmse.write_html(plot_dir / "rmse_comparison.html")
    print("Saved:", plot_dir / "rmse_comparison.html")

    fig_rank = px.line(
        pub_summary.sort_values(["horizon", "mean_rmse"]),
        x="horizon",
        y="mean_rmse",
        color="model_col",
        line_dash="source",
        markers=True,
        title="RMSE Trend Across Horizons"
    )
    fig_rank.write_html(plot_dir / "rmse_trend.html")
    print("Saved:", plot_dir / "rmse_trend.html")

# Final run manifest
manifest = pd.DataFrame([
    {"artifact": "brain_automl_volatility_leaderboard.csv"},
    {"artifact": "best_model_per_stock_rmse.csv"},
    {"artifact": "overall_best_models_rmse.csv"},
    {"artifact": "garch_egarch_metrics.csv"},
    {"artifact": "combined_volatility_metrics.csv"},
    {"artifact": "publication_summary_by_horizon.csv"},
    {"artifact": "plots/rmse_comparison.html"},
    {"artifact": "plots/rmse_trend.html"},
])
manifest.to_csv(OUTPUT_DIR / "run_manifest.csv", index=False)
print("Saved:", OUTPUT_DIR / "run_manifest.csv")
display(manifest)

Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/plots/rmse_comparison.html
Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/plots/rmse_trend.html
Saved: /Volumes/MacSSD/01_Projects/Chandravesh-ML-Research/projects/core-research/brain-ai/examples/volatility_output/run_manifest.csv

                                  artifact
0  brain_automl_volatility_leaderboard.csv
1            best_model_per_stock_rmse.csv
2             overall_best_models_rmse.csv
3                 garch_egarch_metrics.csv
4          combined_volatility_metrics.csv
5       publication_summary_by_horizon.csv
6               plots/rmse_comparison.html
7                    plots/rmse_trend.html